### ISSUE TITLE
How viable is the name "support" in repositories?

### ISSUE THREAD

**Issue by stemount** [EddieJaoudeCommunity/support#1]
1. Would it make sense for folks to fork this support repository, would it be easier for an issue queue to be in one place?
2. How could we get the issue queue into Discord support channels?

**Comment by stemount** [comment]
sounds like support was a good name tbh its clear its not just for support for just the eddie stuff but everything. closing@!

**Comment by eddiejaoude** [comment]
everything is for **our** stuff 🤓 - I am just starting the conversation
