### ISSUE TITLE
please review my Website

### ISSUE THREAD

**Issue by gaushikmr** [EddieJaoudeCommunity/support#10]
https://github.com/gaushikmr
http://gaushik.netlify.app

**Comment by AllanRegush** [comment]
Looks pretty neat! 

On your landing page as a User I feel like I should be able to click on 'Web Designer", "App Developer", "Machine Learning Enthusiast" and be sent to your projects.

Do you have a link to the source code?

**Comment by gaushikmr** [comment]
@AllanRegush nop i dont have any so i mentioned

**Comment by gaushikmr** [comment]
@AllanRegush soon i will link

**Comment by gagangaur** [comment]
animations are good but this looks overly animated work improving the readability so that the visitor doesn't have to do much hard work while going through your site.
