### ISSUE TITLE
How will I be able to contribute to the organization/community?

### ISSUE THREAD

**Issue by HeeteshSimon** [EddieJaoudeCommunity/support#100]
Well it's never late to start learning, so it's never late to start contributing for open source! So I know about "when" but I would like to know about "How". How will I be able to contribute to the organization/community?

**Comment by eddiejaoude** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people
