### ISSUE TITLE
Joining the Community

### ISSUE THREAD

**Issue by vivmost** [EddieJaoudeCommunity/support#102]
I'd love to join your organization.

**Comment by eddiejaoude** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

**Comment by vivmost** [comment]
Okay , Thanks .
