### ISSUE TITLE
Hi Community !

### ISSUE THREAD

**Issue by Shanmuganathanb** [EddieJaoudeCommunity/support#103]
Hi Eddie.. This is Shanmuganathan . I would like to join the community and learn. This is my personal account, which will be always with me and will surely be helpful for the community.

**Comment by eddiejaoude** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people
