### ISSUE TITLE
Contribute to open source

### ISSUE THREAD

**Issue by harshitparwal** [EddieJaoudeCommunity/support#105]
Hey, I want to contribute to open source. I just don't know the right way and the procedure to do so.

**Comment by eddiejaoude** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practicing:
1. Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
2. Practice repo, instructions how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice

Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by eddiejaoude** [comment]
@harshitparwal I will close this for now, as I have added you to our GitHub Organisation. If you have anymore questions, feel free to chat to us in the Discord or even better, raise a Discussion which similar to Issues but allows for threaded conversations - you will still get a green square activity on your GitHub profile for starting a new Discussion https://github.com/EddieJaoudeCommunity/support/discussions
