### ISSUE TITLE
Learn more about open source

### ISSUE THREAD

**Issue by AngelDhakal** [EddieJaoudeCommunity/support#106]
One of my goals of 2020 is to contribute more to opensource, so i wanna join this community to interact with more people and learn more about open source

**Comment by eddiejaoude** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community 🎉 Lets get you involved more in Open Source 💪 

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people
