### ISSUE TITLE
Updating GitHub username shows both old and new in my pull request

### ISSUE THREAD

**Issue by gaushikmr** [EddieJaoudeCommunity/support#11]
[https://github.com/TesseractCoding/NeoAlgo/pull/230](url)
![image](https://user-images.githubusercontent.com/59677936/88831585-88001980-d19d-11ea-9d8c-70bdcbabf552.png)
my old and new usernames

**Comment by gaushikmr** [comment]
[https://github.com/TesseractCoding/NeoAlgo/pull/230](url)
![image](https://user-images.githubusercontent.com/59677936/88831585-88001980-d19d-11ea-9d8c-70bdcbabf552.png)
my old and new usernames

**Comment by eddiejaoude** [comment]
*Note: I moved the comment from the author to the issue description*

**Comment by eddiejaoude** [comment]
If your new (current) GitHub username is `gaushikmr`, GitHub has updated your GitHub profile, but your git commits will still be with the previous GitHub username. For existing Pull Requests this will not change.

Do you have this problem for new Pull Requests with new commits?

**Comment by gaushikmr** [comment]
@eddiejaoude NO

**Comment by eddiejaoude** [comment]
ok no need to shout, just trying to help 😞 

I have seen this before when `git` user doesn't match the `GitHub` user. What is your git user locally?

**Comment by gaushikmr** [comment]
@eddiejaoude gaushikmr

**Comment by gaushikmr** [comment]
@eddiejaoude Gaushik M.R

**Comment by eddiejaoude** [comment]
You answered `no`, but you do have commits from both your different usernames in there, so it will show both

<img width="1259" alt="Screenshot 2020-07-29 23 01 01" src="https://user-images.githubusercontent.com/624760/88858123-70ea1780-d1ef-11ea-80ca-6b4df29b5572.png">

**Comment by gaushikmr** [comment]
@eddiejaoude ok
