### ISSUE TITLE
Can't npm install within Vagrant machine (Laravel) 

### ISSUE THREAD

**Issue by natelloyd1** [EddieJaoudeCommunity/support#12]
![Screenshot 2020-07-30 at 14 47 37](https://user-images.githubusercontent.com/57069051/88930865-fadbc400-d273-11ea-9c43-09a9aeb7d597.png)

I'm trying to set up Passport with Laravel, I've followed along with the initial set up instructions from the docs.  Once I've run - 

php artisan vendor:publish --tag=passport-components and added the components to the resources/js/app.js file. 

It then wants my to run 'npm run dev' however I just get a list of errors such as 

'sh: 1: cross-env: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT'

**Comment by eddiejaoude** [comment]
@natelloyd1 can you share what you have in the `package.json` file

**Comment by natelloyd1** [comment]
![Screenshot 2020-07-30 at 14 57 23](https://user-images.githubusercontent.com/57069051/88931628-febc1600-d274-11ea-9601-6e8f648681da.png)

**Comment by stemount** [comment]
@natelloyd1 ahh, [adds some context here, this is a Homestead VM]

you need to be in the directory where the site is, the ENOENT suggests it can't find that file,
you'll find this in your homestead yaml it will generally be a case of switching to `/mnt/something, /var/www/, /srv/` something

**Comment by eddiejaoude** [comment]
I think there are a few issues, but lets start off with issue 1 as others might become less of an issue later on.

`npm install` can not find `package.json`, you need to run the command in the same directory

**Comment by natelloyd1** [comment]
OK, so it looks like it is in the same directory that I'm running the command in, see img. 
![Screenshot 2020-07-30 at 15 08 08](https://user-images.githubusercontent.com/57069051/88932926-a7b74080-d276-11ea-9288-f4264b418213.png)

**Comment by natelloyd1** [comment]
Oh sorry, just seen @stemount 's comment. Hang on.

**Comment by natelloyd1** [comment]
So I change this file path here to something like: /mnt/something, /var/www/, /srv/?
![Screenshot 2020-07-30 at 15 14 10](https://user-images.githubusercontent.com/57069051/88933602-89057980-d277-11ea-8ba0-47935ad2e64e.png)

**Comment by alrifay** [comment]
I found another issue similar to yous.
>Does providing the `--no-bin-links` option to `npm install` solve your issue?
_Originally posted by @goloroden in https://github.com/npm/npm/issues/7308#issuecomment-73489075_

Delete `node_modules` directory and try this command `npm install --no-bin-links`

**Comment by natelloyd1** [comment]
thanks @alrifay. Didn't seem to work for me, see below - 
![Screenshot 2020-07-30 at 17 01 52](https://user-images.githubusercontent.com/57069051/88945884-70e92680-d286-11ea-843b-9d9cb63f482c.png)

**Comment by stemount** [comment]
Destroying your Homestead box and recreating it may help, NFS may have fallen over here, so you can restart NFS and maybe the machine. An off and on job hopefully...

**Comment by eddiejaoude** [comment]
I remember from my time with vagrant many years ago, if commands were mix (run on local and in vm), then it would cause the project to break.

**Comment by alrifay** [comment]
I think the issue is in the path because you are using window.

I found this in [Laravel documentation - homestead](https://laravel.com/docs/7.x/homestead#configuring-homestead): 
>Windows users should not use the ~/ path syntax and instead should use the full path to their project, such as C:\Users\user\Code\project1.

**Comment by natelloyd1** [comment]
Ok thanks. I tried many things, such as clearing the npm cache and re-installing many times but no joy. Then I deleted the package.json and couldn’t seem to recover the VM...

So at the point of no return I’ve started again in another project and I seem to have it working now. Thanks for all your help!

**Comment by natelloyd1** [comment]
On another project now and ran 'npm install and npm run dev' within the directory - got errors.  

Then I tried 'npm install', **closed** VS Code, then went back into the directory and successfully compiled the project with 'npm run dev'.  

Not sure this will help anyone but I think it helped me. 
<img width="605" alt="Screenshot 2020-08-03 at 13 55 22" src="https://user-images.githubusercontent.com/57069051/89184610-00494f00-d591-11ea-9ea5-d06618696e5f.png">
