### ISSUE TITLE
I would like to be part of your community. Please add me!!

### ISSUE THREAD

**Issue by Krishna-Ravi** [EddieJaoudeCommunity/support#129]
**Description**

Was inspired by one of your live sessions with Praveen Kumar. 
From there I went on exploring about Github and also customized my github readme. 

Please have a look at my github readme once. 
https://github.com/Krishna-Ravi

Thanks EddieJaoude

**Comment by eddiejaoude** [comment]
Your GitHub custom profile looks good 👍 - I keep changing my all the time and making tweaks

Invitation sent for the GitHub Organisation. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practicing:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
