### ISSUE TITLE
Typo in Issue templates

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/support#136]
In the templates files `Eddie Jaoude` is spelt wrong on the last line https://github.com/EddieJaoudeCommunity/support/tree/main/.github/ISSUE_TEMPLATE

For example, it is

```markdown
Feel free to check out other cool repositories of EddieJoaude Community [here](https://github.com/EddieJaoudeCommunity)
```

But should be 

```markdown
Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)
```

I added a space too between first name and last name for readability

**Comment by tory-brown** [comment]
ok thanks, i'll get to it now

**Comment by eddiejaoude** [comment]
Awesome @tory-brown , thank you 🤓 . You can raise a PR for each file or do it all in one PR, whichever you prefer. Any question just let us know :)

**Comment by VictoryWekwa** [comment]
Hello, is this issue still open?

**Comment by eddiejaoude** [comment]
I just check the files in the link in the description and yes it looks like it is 👍

**Comment by VictoryWekwa** [comment]
okay.
Can I work on it?

**Comment by eddiejaoude** [comment]
Sure, I think @tory-brown who it was initially assigned to 10 days has got busy and hopefully won't mind 🤓

**Comment by VictoryWekwa** [comment]
Okay. Thanks, will gt to it immediately

**Comment by VictoryWekwa** [comment]
@eddiejaoude I raised a PR kindly review. Thank you :slightly_smiling_face:

**Comment by eddiejaoude** [comment]
Thank you @VictoryWekwa , already reviewed and merged 🤓
