### ISSUE TITLE
Automate the process of adding new users to the organization

### ISSUE THREAD

**Issue by alrifay** [EddieJaoudeCommunity/support#137]
Edit:

@AllanRegush found a github action [ActionsDesk/invite-user](https://github.com/ActionsDesk/invite-user) that invites new users

---

> 
> I read the discussion here https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io/issues/35#issuecomment-684839794 
> And i found we can use [github octokit](https://github.com/octokit/rest.js) to invite new members to the organization.
> 
> There is two functions, i'm not sure which one we should use 😁
> - [Create an organization invitation](https://octokit.github.io/rest.js/v18#orgs-create-invitation)
> - [Set organization membership for a user](https://octokit.github.io/rest.js/v18#orgs-set-membership-for-user)
> 
> We can create a GitHub actions that triggers on new issues and add the issue author if the issue has a specific title 
> for example: `add me to the organization`

**Comment by eddiejaoude** [comment]
Thanks @alrifay 👍

**Comment by AllanRegush** [comment]
This github action might not fit our needs. Consider forking the project and making the action query the api for missing information. i.e. email

**Comment by eddiejaoude** [comment]
We still need this, I remove the `no-issue-activity` label

**Comment by BOLT04** [comment]
This is still relevant stale bot

**Comment by eddiejaoude** [comment]
This has been done in #718 - still needs testing

**Comment by eddiejaoude** [comment]
This works 👍 I am going to close
