### ISSUE TITLE
still i'm not sure how to join ..can anyone explain how ..I mean becoming a member in the organization

### ISSUE THREAD

**Issue by Arvindjitta** [EddieJaoudeCommunity/support#139]
**Description**

still i'm not sure how to join ..can anyone explain how ..I mean becoming a member in the organization

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
@Arvindjitta I just sent the invitation for the GitHub Organisation. Welcome to the community 🎉. Any issues let us know 🤓 

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practicing:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by eddiejaoude** [comment]
<img width="971" alt="Screenshot 2020-09-02 at 09 53 43" src="https://user-images.githubusercontent.com/624760/91960802-40bbfa00-ed02-11ea-8cd6-22a2875096e8.png">

You will get an email to accept the invitation.
