### ISSUE TITLE
What are teams used for in the EddieJaoude community organisation ? 

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#14]
I just saw in eddy community memeber's list there's a column named team, and u don't know what's that for 

<img width="1078" alt="Screenshot 2020-07-30 at 19 18 23" src="https://user-images.githubusercontent.com/624760/88959197-8582ea00-d299-11ea-810f-6454068c0f73.png">

**Comment by eddiejaoude** [comment]
**Teams** are for assigning people more access to projects, so they do not need to be forked and can be contributed to directly (PRs with branches are still required for everyone).

**Comment by mohit01-beep** [comment]
And what's fork do?🙁 Sorry if I bother you just so many questions 😅

**Comment by Ruth-ikegah** [comment]
@mohit01-beep to fork a project means to have a copy of the project as your own. Like a photocopy of the project as your own. In contributing to open source projects, you will most times have to fork the repository to make changes to it. Feel free to ask more questions.
