### ISSUE TITLE
" Failed to compile " error..I am stuck please can someone help

### ISSUE THREAD

**Issue by Naeemah-Khatib** [EddieJaoudeCommunity/support#145]
**Description**

I have just started to work with Angular, and while configuring it I got the following error,
" Failed to compile.
./node_modules/style-loader/lib/addStyles.js
Module build failed: Error: ENOENT: no such file or directory, open 'F:\Coursera\Angular\conFusion\node_modules\style-loader\lib\addStyles.js' "

**Working Environment**

Operating System: Windows

Browser : Chrome

Device : Laptop

**Screenshots**

![image](https://user-images.githubusercontent.com/61241046/92025128-b49ae880-ed7c-11ea-91f9-b3d2ada316c9.png)

Please help me out.........thank you

**Comment by eddiejaoude** [comment]
how did you create the project, was it using the Angular CLI? Or is it an existing project.

I suggest running `npm install`

**Comment by Naeemah-Khatib** [comment]
> how did you create the project, was it using the Angular CLI? Or is it an existing project.
> 
> I suggest running `npm install`

I created it using Angular CLI

**Comment by Naeemah-Khatib** [comment]
@eddiejaoude 
After running npm install ,
the next command was "ng serve" but an exception occured
![image](https://user-images.githubusercontent.com/61241046/92075597-6c101900-edd6-11ea-892e-7122a773226d.png)

**Comment by eddiejaoude** [comment]
Hmm I have never had an issue using the CLI. Lets check a few things...

These are the steps I would do, you might have done them already, can you check the version number as we go along, I will add the commands:

1. `node --version`
2. `npm --version`
3. `npm install -g @angular/cli`
4. `ng --version`
5. `ng new app-name`
6. `cd app-name`
7. `ls -la`
9. `cat package.json`
10. `ng serve --open`

Please share the terminal output from the above commands (copy and paste will probably be better than screenshot)

**Comment by eddiejaoude** [comment]
And if you try `ng serve` again do you still get the same error?

I wonder if the camel case of the project name could be causing an issue.

Try creating a new project called `fusion`

**Comment by Naeemah-Khatib** [comment]
No I'm not getting an error now, everything is working cool.

Thanks a lot..... @eddiejaoude

**Comment by eddiejaoude** [comment]
Ok great 👍 , I will close the issue
