### ISSUE TITLE
 i want to join GitHub Org community

### ISSUE THREAD

**Issue by AnkushSinghGandhi** [EddieJaoudeCommunity/support#166]
i want to join GitHub Org community

**Comment by AnkushSinghGandhi** [comment]
actually i dont understand how to join your community or understand about this community thing ughh..
i raised an issue as you said i got this invite message when i click on github organization link it takes me to https://github.com/EddieJaoudeCommunity

**Comment by eddiejaoude** [comment]
@AnkushSinghGandhi I just sent you an invite and replied in your other issue here https://github.com/EddieJaoudeCommunity/support/issues/165

**Comment by AnkushSinghGandhi** [comment]
now i got it thanx a lot

**Comment by eddiejaoude** [comment]
ok great 👍
