### ISSUE TITLE
which language is used to develop desktop apps(mainly for windows)?

### ISSUE THREAD

**Issue by ThatOneTallKid** [EddieJaoudeCommunity/support#171]
I want to develop an app for PC.

**Comment by rohitv-dev** [comment]
I personally use ElectronJS, but it's pretty heavy. Consumes lots of memory, but has good features. For a light weight alternative, I am having a look at React NodeGUI.

**Comment by AllanRegush** [comment]
For windows I'd recommend C#. What language are you most conformable with?

**Comment by ThatOneTallKid** [comment]
Like, actually I don't know anything about this topic.
I am comfortable with c++, JavaScript, dart(flutter) and python.

**Comment by AllanRegush** [comment]
Tons of options for you. 
There is:
C++
win32 api : https://docs.microsoft.com/en-us/windows/win32/
C++/CLI aka c++ in .net ( sorry don’t have a link)
Wxwidgets: https://www.wxwidgets.org/
Qt: https://www.qt.io/
JavaScript
Electron: https://www.electronjs.org/
Python
Tkinter : https://docs.python.org/3/library/tkinter.html
Kivy: https://kivy.org/#home
Qt

There is more. Best to find what your needs and interests are and pick one.

**Comment by ThatOneTallKid** [comment]
thanks @AllanRegush , that's a lotta help.

**Comment by ThatOneTallKid** [comment]
Can anyone tell when i will get added to the community organization?

**Comment by eddiejaoude** [comment]
@ThatOneTallKid can you create an issue asking to be added to the organisation https://github.com/EddieJaoudeCommunity/support

**Comment by ThatOneTallKid** [comment]
I created! @eddiejaoude
