### ISSUE TITLE
What is fork used for?

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#19]
@mohit01-beep to fork a project means to have a copy of the project as your own. Like a photocopy of the project as your own. In contributing to open source projects, you will most times have to fork the repository to make changes to it. Feel free to ask more questions.

_Originally posted by @Ruth-ikegah in https://github.com/EddieJaoudeCommunity/support/issues/14#issuecomment-666740486_

**Comment by eddiejaoude** [comment]
> beep to fork a project means to have a copy of the project as your own. Like a photocopy of the project as your own. In contributing to open source projects, you will most times have to fork the repository to make changes to it. Feel free to ask more questions

By @Ruth-ikegah
