### ISSUE TITLE
Eddie change the comment section covering your face

### ISSUE THREAD

**Issue by vamsi963601** [EddieJaoudeCommunity/support#191]
**Description**

A brief description of the question or issue:
Please take the comment section to the right of the video in your livestreams.

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Duplicate of #192
