### ISSUE TITLE
Eddie the comments overlay is covering your face

### ISSUE THREAD

**Issue by sbdeepu09** [EddieJaoudeCommunity/support#192]
**Description**

A brief description of the question or issue, also include what you tried and what didn't work:

**Stack**

Project stack or language (eg. Frontend):

**Working Environment**

Operating System (eg Linux):

Browser (eg. Chrome):

Device (eg. Laptop or Phone):

**Screenshots**

![Screenshot from 2020-09-15 19-45-06](https://user-images.githubusercontent.com/56597366/93222049-1cddc700-f78c-11ea-9399-eba6cbbfdb56.png)

[Optional] **Additional Context**

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
We still need this stalebot 🤓

**Comment by Vyvy-vi** [comment]
I think, this is still needed
