### ISSUE TITLE
Hey there! Would love to be part of this organization

### ISSUE THREAD

**Issue by NirmalSilwal** [EddieJaoudeCommunity/support#193]
**Description**
Hello,

Watched the live stream today on YouTube. Really get interested during that stream. I would love to be the part of this organization. Looking forward to contribute actively and be part of this great community.

Seems this would be exciting community to engage on!

Can I be the part of the organization?

![pull request merged](https://user-images.githubusercontent.com/31946761/93236809-e65c7800-f79c-11ea-8f17-efa07f3387cd.gif)

Best
Nirmal

**Comment by eddiejaoude** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practicing:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by NirmalSilwal** [comment]
Thanks once again @eddiejaoude for having me in the organization.

Thanks for the tips too. Looking forward to collaborate and add value in the community.
