### ISSUE TITLE
I would like to join

### ISSUE THREAD

**Issue by oluwoleilesanmi** [EddieJaoudeCommunity/support#199]
Goals 

- Join this organisation.
- Contribute to this organisation.

**Comment by oluwoleilesanmi** [comment]
Great, i have joined the discord chat.

**Comment by eddiejaoude** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practicing:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by eddiejaoude** [comment]
Great to have you in our Discord too! Thank you for raising the question about the label. I have now created a Pull Request that is in review to improve this, if you would like to take a look, here it is https://github.com/EddieJaoudeCommunity/support/pull/202/files
