### ISSUE TITLE
What is the best "template" for "asking a question"?

### ISSUE THREAD

**Issue by stemount** [EddieJaoudeCommunity/support#2]
We need an issue template so that we can have things like "terms people would search for", ensure that there is enough information.

Extreme ideation: A bot would probably need to come along and try and see if folks haven't followed the template...

Suggestions welcome!

**Comment by eddiejaoude** [comment]
Templates are really important here 👍 . We probably need a few like:

- Add me to the community organisation 
- How do I ...?
- Please review my GitHub profile / open source project
- ...

**Comment by Ruth-ikegah** [comment]
I can help on making this issue template @eddiejaoude

**Comment by eddiejaoude** [comment]
@Ruth-ikegah awesome 👍 - yes please 🤓 

I do not think we will get this perfect first time, so lets put something together, get it merged in and keep iterating and improving it as we think of new ideas 😄

**Comment by stemount** [comment]
I think we can close this @eddiejaoude! The issue templates are looking good, @eddiejaoude I didn't wanna change it just in case you have a clone?

![image](https://user-images.githubusercontent.com/150512/89463013-2ffd8000-d766-11ea-8f04-b6317575af08.png)

**Comment by stemount** [comment]
This would be a good place to practice a PR, so when we have anyone new to using github UI/PRs we can use as a good first issue! Reinforces that documentation is as good as code!

**Comment by eddiejaoude** [comment]
Good spot on the typo. We can raise a new issue and yes it is a good first PR 👍
