### ISSUE TITLE
I want to upload a folder in repository, but I can't able to add folder it only uploads file but my css file is in a folder. I want to upload the folder as it is 

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#20]
**Description**

A brief description of the question or issue:

**Stack**

Project stack or language (eg. Frontend):

**Working Environment**

Operating System (eg Linux):

Browser (eg. Chrome):

Device (eg. Laptop or Phone):

**Screenshots**

Please add a screenshot if applicable

[Optional] **Additional Context**

**Comment by eddiejaoude** [comment]
- What have you tried that doesn't work for folders? 
- Are you using a GUI or a CLI
- What OS are you on? Linux, Mac, Windows
- **anymore useful information to share with us...**

**Comment by AllanRegush** [comment]
I think what is happening is the folder is the root for this repository. You can try making a folder in that directory and moving the css file into there.

**Comment by mohit01-beep** [comment]
> **Please provide more information for us to help, here are some suggestions...**
> 
> * What have you tried that doesn't work for folders?
> * Are you using a GUI or a CLI
> * What OS are you on? Linux, Mac, Windows
> * _anymore useful information to share with us_

i got it later that i can drag and drop folders in repository

**Comment by s4satishkumar** [comment]
thanks ;) i also got confused i did why not happening now 😃. thanks @mohit01-beep
