### ISSUE TITLE
Add me to your Organization.

### ISSUE THREAD

**Issue by aniketsingh98571** [EddieJaoudeCommunity/support#200]
Hey all, My name is Aniket Singh. I am a Computer Science student at Sandip Institute of Technology and Research Center. My personal area of interest is Web Development. I love to code and play around it, I am part of Scaler Academy and Girlscript foundation. Helping others is my hobby. Recently I have taught students, "How to contribute to Open Source"?
Github-https://github.com/aniketsingh98571
Linkedin-https://www.linkedin.com/in/aniket-singh-968687199/
Twitter-https://twitter.com/anikets63437544

**Comment by eddiejaoude** [comment]
Invitation sent for the GitHub Organisation. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practicing:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
