### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by h3cksamrat** [EddieJaoudeCommunity/support#206]
**Description**

A brief description of the question or issue:
Hello, I am new to open source I don't understand anything but want to get hands-on it. How can I make the organization set to public and how to make contributions?

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by AllanRegush** [comment]
Welcome! :tada: 

I see that you have added to join in this issue: https://github.com/EddieJaoudeCommunity/support/issues/206
Eddie will accept when he is available.

You can make the organization public by: 
Going on to our community page: https://github.com/EddieJaoudeCommunity

Click on people in this box:

![Screenshot_20200916_230238](https://user-images.githubusercontent.com/17693494/93422448-09f0f280-f871-11ea-94d8-c48924a0222e.png)

Search for yourself in this input:

![Screenshot_20200916_230735](https://user-images.githubusercontent.com/17693494/93422822-debad300-f871-11ea-8eb5-ad472b26086d.png)

Click Private (Default - I have it set to public).
Select if you would like it be public or private.

![Screenshot_20200916_231045](https://user-images.githubusercontent.com/17693494/93422970-26d9f580-f872-11ea-870d-4406db20e9d5.png)

<br />

How do get started? Your doing it! :+1: :tada: 
Have you joined our [Discord](https://discord.com/invite/jZQs6Wu)?

You can make your first pull request in this [repository](https://github.com/EddieJaoudeCommunity/hacktoberfest-practice)
Follow the instructions in the readme. If you have any trouble you can ask questions in our Discord.

I hope this helps you out! :nerd_face:

**Comment by eddiejaoude** [comment]
@AllanRegush awesome reply 👍 . We need to capture that in the README.md 

@h3cksamrat I am going to close this Issue, but feel free to create another Issue or Discussion with a more specific question (plus you will get another green square 🟩 )
