### ISSUE TITLE
Update main.yml

### ISSUE THREAD

**Issue by nawalhmw** [EddieJaoudeCommunity/support#209]
**Description**

Update line 10 in the **_awesome-github-profiles_** repo from [here](https://github.com/EddieJaoudeCommunity/awesome-github-profiles/blob/1ffa478f0e23995b4776ecd1c97dcecc4267b993/.github/workflows/main.yml#L10) to 

+ uses: EddieJaoudeCommunity/gh-actions-html-table-generator@v0.1

**Working Environment**

Operating System (eg Linux):
Windows 10

Browser (eg. Chrome):
Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)

Device (eg. Laptop or Phone):
Laptop

**Comment by eddiejaoude** [comment]
Thank you @nawalhmw 👍

**Comment by VictoryWekwa** [comment]
Hello, please can I work on this?

**Comment by eddiejaoude** [comment]
Thanks @VictoryWekwa I think that has been done now, so I will close https://github.com/EddieJaoudeCommunity/awesome-github-profiles/blob/main/.github/workflows/main.yml#L10
