### ISSUE TITLE
Add "How do I get started with open source?" to FAQ

### ISSUE THREAD

**Issue by BOLT04** [EddieJaoudeCommunity/support#236]
**Description**

Most newcomers ask this question, and we have had community members answer them both in Discord and on other issues (e.g. [this one](https://github.com/EddieJaoudeCommunity/support/issues/206)). It would be more helpful to have this question on FAQ.

**Discord answer example**
![imagem](https://user-images.githubusercontent.com/18630253/93710478-14e0a700-fb3f-11ea-86c8-5d62406dcc16.png)

What do you think?

**Comment by eddiejaoude** [comment]
Yep, we should collect the common questions and add them to the FAQ 👍

**Comment by BOLT04** [comment]
awesome, can you assign this issue to me @eddiejaoude? I'd like to work on it 😃.

**Comment by eddiejaoude** [comment]
Sure 👍 , thank you 👍
