### ISSUE TITLE
Created an Automation of Facebook Comment for Social Media Movement

### ISSUE THREAD

**Issue by h3cksamrat** [EddieJaoudeCommunity/support#243]
Items we can review on a live stream:

- Open source project
    https://github.com/h3cksamrat/FacebookAutomatedComment

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
In the README I think it needs to say more about what the project does

**Comment by BOLT04** [comment]
@h3cksamrat you can add a License that helps you to say this "PS. You are responsible for the way you use the software.", like the MIT Licence 😃.

**Comment by h3cksamrat** [comment]
@BOLT04 Thank you for your suggestions. I'll take a look at the resources and value you provided.
