### ISSUE TITLE
Please add me to the organisation 

### ISSUE THREAD

**Issue by ugglr** [EddieJaoudeCommunity/support#26]
**Description**

I'll join the fun, if you'll let me 🥺

**Comment by AllanRegush** [comment]
@ugglr Suggestion: change the label to `invite me to the organization`. see #21. Then @eddiejaoude might see this sooner.

**Comment by eddiejaoude** [comment]
Oops, sorry @ugglr I did miss this. Thank you @AllanRegush 👍 

I will send you an invite now 🎉

**Comment by eddiejaoude** [comment]
Sent 🎉
