### ISSUE TITLE
Is adding a tool that helps newcomers using the commit guidelines helpful?

### ISSUE THREAD

**Issue by BOLT04** [EddieJaoudeCommunity/support#260]
**Description**

Recently I stumbled upon a repository with instructions on [how to contribute](https://github.com/madlabsinc/teachcode#how-should-i-write-a-commit-message) to the project. We tend to use the same guidelines on the community's repositories, so a tool like this could be beneficial to us as well.

On some repositories, I think this isn't as important, and leaving the commit message to the contributor is the easiest option. But for EddieBot or EddieBotUI, I think this is useful. Actually I believe we are using [husky](https://github.com/typicode/husky) in EddieBotUI, but I think it's a tool that only allows valid commits, but I'm not sure.

**Goal**
The goal is to **help any contributor** who is new to open source or is not aware of these guidelines. I think we should try to avoid enforcing this style on new contributors, since it just becomes a new barrier to entry if their commits get blocked by a tool. Instead, the tool would give a **hint** of how to write a commit message that adheres to the guidelines of the repo.

With the upcoming of [Hacktoberfest](https://github.com/EddieJaoudeCommunity/hacktoberfest-practice) most repositories adhere to these (or other) guidelines, so I think including a tool like [commitlint](https://github.com/conventional-changelog/commitlint/#what-is-commitlint) would help members of the community to prepare for contributions to the majority of repos out there.

I'm very keen to hearing everybody's thoughts on this 😃. If you like this idea, please comment suggestions in the comments. For example, we could have a GitHub action that runs this linter, but instead of failing the build and blocking the PR, it would be a warning or information (like if it were log levels, instead of `error` it's `info` 😄).

**Resources**:
- https://github.com/conventional-changelog/commitlint/#what-is-commitlint
- https://www.conventionalcommits.org/en/v1.0.0/

**Comment by eddiejaoude** [comment]
I am a fan of standards/consistency, with things like `conventional-changelog`. With some of our repos like `hacktoberferst-practice` and `awesome-github-profiles`, I have been quite relax. 

On EddieBot where good commit comments are more useful, I have been squashing when merging PRs in, so I can rewrite the commit message without bothering people.

Maybe we have a standard and try to help people conform to it, but also don't block people as we can squash PRs and add our own commit message.

**Comment by BOLT04** [comment]
@eddiejaoude do you think it's worth experimenting with a tool like this? Like an experiment with a tool that would run checks after the user made a commit, and if it doesn't use the standards it would print an info message with instructions on how to do so? The commit would still be made and it doesn't block the PR, but it helps the user know what are the standards used.

**Comment by eddiejaoude** [comment]
yeah sounds like a good idea 👍 . There is an existing GitHub Action we could use https://github.com/marketplace/actions/commit-linter

**Comment by BOLT04** [comment]
@eddiejaoude what do you think about closing this issue, since we added commitzen on EddieBot?

**Comment by eddiejaoude** [comment]
@BOLT04 yeah you are right 👍 - we can always re-open  / create a new one if needed
