### ISSUE TITLE
Please review my profile

### ISSUE THREAD

**Issue by gaushikmr** [EddieJaoudeCommunity/support#27]
https://github.com/gaushikmr

**Comment by mikeysan** [comment]
Hey, @gaushikmr Very good profile. Way better...actually, I can't compare as I don't even have one. The only thing that jumps out at me is the [helo].gif. I find that too distracting; making it difficult to calmly read the rest of what you have written. I would either remove it or create a slower version.

**Comment by eddiejaoude** [comment]
Good point @mikeysan 👍  

Also maybe don't make it loop? or loop with a limited amount of 2?

**Comment by gaushikmr** [comment]
@eddiejaoude Can u check now.

**Comment by eddiejaoude** [comment]
Looks good 👍

**Comment by AllanRegush** [comment]
Looks good to me. I saw one spelling error. I raised an issue and made a PR. :+1:

**Comment by eddiejaoude** [comment]
@gaushikmr can this now be closed?
