### ISSUE TITLE
How to contribute my GitHub profile to the awesome-github-profiles repo

### ISSUE THREAD

**Issue by DevItsMB** [EddieJaoudeCommunity/support#28]
As the title says, how to add my profile to the table over at the readme.
Could you guide me through?

My screenshot:
![DevItsMB](https://user-images.githubusercontent.com/58613756/89167056-37146a80-d57b-11ea-892c-bf5c78f23acd.png)

**Comment by DevItsMB** [comment]
Hey, as I mentioned above. Coudl you explain me how to contribute my GitHub profile to the awesome-github-profiles repo?

**Comment by eddiejaoude** [comment]
From the current documentation...

> 1. create an issue, with the title as your name, and in the description put a screenshot of the customised GitHub profile page
> 2. take the url created by github from the screenshot in step 1 and add it to this `README.md` as an image at the bottom of the table (use other submissions with the table as an example)
> 3. use your created issue url under the image you added

Great question 👍 , after this discussion I am sure there are more improvements we can make to the documentation

From looking at your profile, I have put green tick ✅  on the steps I think you have already done: 

1. ✅ Create an issue on that the [awesome-github-profiles](http://github.com/EddieJaoudeCommunity/awesome-github-profiles) repo with your screenshot, **before submitting the issue, copy the generated image url** *(don't worry if you have submitted it, you can click `edit` to get the url afterwards)*
2. ✅ Go back to the `README.md` file, and at the top right click the `edit` icon (looks a bit like ✏️ )
3. ✅ GitHub will **fork** the project which means to make a copy for you, then you can make yours changes to the `README.md`, then **commit** to save (these are still currently in your **fork**)
4. Next is to create a **Pull Request** on the source project for review and approval

**Comment by DevItsMB** [comment]
@eddiejaoude Okay thanks, so I need to pull a request here: https://github.com/EddieJaoudeCommunity/support/pulls ?

**Comment by eddiejaoude** [comment]
Yes 👍 . Raise a pull request there, which means you are requesting changes from your forked repo to the main/source repo for review

**Comment by DevItsMB** [comment]
Okay thanks, one more question. What should I select at "Comparing changes". If you can tell what I need to enter there, that would help me out. I never pulled a request, that's why I am so confused
![Annotation 2020-08-03 131822](https://user-images.githubusercontent.com/58613756/89177458-d5103100-d58b-11ea-8dfb-9510001a9119.png)

**Comment by eddiejaoude** [comment]
Raising a **pull request** is confusing, you are not alone 🤓 

If you `click` on `compare across forks` you will be given more options

<img width="1228" alt="Screenshot 2020-08-03 at 12 25 06" src="https://user-images.githubusercontent.com/624760/89177978-80b58300-d584-11ea-8a9c-d322a0db6c1e.png">

Which will look like this, then select your branch in your repo that you made changes to

<img width="1316" alt="Screenshot 2020-08-03 at 12 25 19" src="https://user-images.githubusercontent.com/624760/89178002-9034cc00-d584-11ea-839a-9e5f4acbdc3f.png">

**Comment by DevItsMB** [comment]
Okay so I made that issue and now I am about to make that pull request, but I am still confused, I didn't made changes, I created an issue with my screenshot and name,
So I have no clue what to select from there.
Do I need to change the (README.md)[https://github.com/EddieJaoudeCommunity/awesome-github-profiles/blob/master/README.md] and add my stuff?

**Comment by eddiejaoude** [comment]
From your **fork** (copy) of the repo in your GitHub account, it looks like you have made a **branch** with your changes...

<img width="1803" alt="Screenshot 2020-08-03 at 12 49 03" src="https://user-images.githubusercontent.com/624760/89179552-da6b7c80-d587-11ea-8716-adf91ae65fa7.png">

So you need to raise a **Pull Request** like in my previous comment so it can be reviewed.

**Comment by DevItsMB** [comment]
@eddiejaoude Done :D.

**Comment by eddiejaoude** [comment]
Awesome 👍 . I will close this then 🤓
