### ISSUE TITLE
Review my open source projects 

### ISSUE THREAD

**Issue by shivambhat** [EddieJaoudeCommunity/support#284]
### **Items** we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thank you 👍 . I will take a look at your open source project in a live stream soon 🤓

**Comment by eddiejaoude** [comment]
Hi, I will be reviewing open source projects on a live stream today at 2pm UK time (2.5 hours from now). 

Here is the YouTube live link https://www.youtube.com/watch?v=LyTUj6YQoBo

**Comment by eddiejaoude** [comment]
@shivambhat please update the title as it does not represent what is in the issue
