### ISSUE TITLE
What PR does exactly do? and what we can do with PR 

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#29]

**Comment by Ruth-ikegah** [comment]
PR means **Pull Request**. 
A  pull request is a method of submitting changes you want to be implemented on a project. Let's say you want to improve a file in this repository, so you have to first **fork** it( download it to have your own copy), then make the changes and create a PR to add your changes to the original repository from your forked repository.
So when a PR is created by you to the original, the owner of the original repository will now **merge** the PR ( merging means adding your changes to the original.

Is this clear enough?

**Comment by mohit01-beep** [comment]
So after changes and when we did PR it's upto owner of that repo that he/she wants to merge that change or not, right?

**Comment by Ruth-ikegah** [comment]
Yes, only the people that own the repo or have write access can merge the PR. 
Just so you know, you can make PR on your own repository and since you are the owner, you have the power to merge them

**Comment by mohit01-beep** [comment]
> Yes, only the people that own the repo or have write access can merge the PR.
> Just so you know, you can make PR on your own repository and since you are the owner, you have the power to merge them

Oh ok now i know what's PR for Thanks @Ruth-ikegah
