### ISSUE TITLE
FAQ: Add "How to look for an open source project to contribute"

### ISSUE THREAD

**Issue by BOLT04** [EddieJaoudeCommunity/support#293]
**Description**
This discussion for this issue started [here](https://github.com/EddieJaoudeCommunity/support/discussions/275) 😃.

**Tasks**
- [x] Add `Finding-Open-Source-Projects.md` at the root level of the repository. I think we don't need a folder to put this file in yet, but let me know what you think in the comments 👍 
- [x] Add the question to the README FAQ and provide a link to the file above

Also, do you have any suggestions for the filename?

**Comment by eddiejaoude** [comment]
I am so bad at naming things, we might need to create it and rename it later - just need to remember where it linked to so we can update those

**Comment by BOLT04** [comment]
yes, we can rename later and change the links 👍. 
I'd like to work on this if no one else wants it. Can you assign this to me @eddiejaoude 😃 ?

**Comment by BOLT04** [comment]
sorry @eddiejaoude, I've only now realized this wasn't assigned 😟. I got too eager to start working on it and forgot about my comment. 
If it's okay, can my PR still be eligible for review? I'm also down to help anyone who comes along and wants to work on this as well 😃.

**Comment by eddiejaoude** [comment]
Great work 👍 - merged 🎉
