### ISSUE TITLE
I have just started with open source. So here is what I want to know that how can I make quality pull requests for #oktoberfest and am I supposed to submit it somewhere for oktoberfest?

### ISSUE THREAD

**Issue by shivambhat** [EddieJaoudeCommunity/support#296]
**Description**

A brief description of the question or issue:

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
I will close this because you already started a Discussion here too https://github.com/EddieJaoudeCommunity/support/discussions/295

Please do not spam in multiple places, your questions will get answered by the community when they have time 🤓
