### ISSUE TITLE
Update README.md so users know exactly what this repo/issue queue/discussion board is for

### ISSUE THREAD

**Issue by stemount** [EddieJaoudeCommunity/support#3]
its just a first draft.

**Comment by stemount** [comment]
- Adding good first issue as this is a documentation change instead of a complex code ticket.
- Changing issue title to make more sense.

**Comment by eddiejaoude** [comment]
> Q: What is the differentiation between the issue queue and discussions at the min?

Yes this is so important to be clear

**Comment by VictoryWekwa** [comment]
Is this still open?
And what is to be done here?

**Comment by eddiejaoude** [comment]
I think more can still be done on this, for example [here](https://github.com/EddieJaoudeCommunity/support#guide) it would be good to also include that in `Discussions` people can show case their open source portfolios to get feedback

**Comment by VictoryWekwa** [comment]
Adding.
`° Showcasing of Open Source Portfolios to get feedback from community members`

Something like that right?

**Comment by eddiejaoude** [comment]
@VictoryWekwa looks good 👍

**Comment by eddiejaoude** [comment]
@VictoryWekwa we never get these things right first time or second, but we can keep making little improvements each time 🤓

**Comment by VictoryWekwa** [comment]
Oh
Okay .... Great😁 Will work on it now and raise a PR
