### ISSUE TITLE
Bootstrap Studio alternative

### ISSUE THREAD

**Issue by JorgePiaggio** [EddieJaoudeCommunity/support#316]
hi, can anyone recommend a free alternative to bootstrap studio? 
i'm just trying to create a layout template for a web page.

**Comment by eddiejaoude** [comment]
I never used bootstrap studio. 

What about tailwind do they have something similar and free?

**Comment by JorgePiaggio** [comment]
the thing is that i don't have much time to get into css.. 
solved it here [OS-Templates](https://www.os-templates.com/free-website-templates)

**Comment by eddiejaoude** [comment]
ok glad you found a solution. I will close this issue
