### ISSUE TITLE
Please review my profile, project and portfolio

### ISSUE THREAD

**Issue by flyingsonu122** [EddieJaoudeCommunity/support#319]
Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Can you share links please to your open source project and portfolio

**Comment by flyingsonu122** [comment]
GitHub link [https://github.com/flyingsonu122/flyingsonu122.github.io](https://github.com/flyingsonu122/flyingsonu122.github.io)


Portfolio link [https://flyingsonu122.github.io/](https://flyingsonu122.github.io/)


GitHub account [https://github.com/flyingsonu122](https://github.com/flyingsonu122)


Portfolio is made using HTML CSS and JavaScript and hosted on GitHub pages
it contains my introduction, social media links and showing my projects

**Comment by eddiejaoude** [comment]
I will update the title

**Comment by eddiejaoude** [comment]
Thank you 👍 . I will take a look at your open source project in a live stream soon 🤓

**Comment by eddiejaoude** [comment]
Hi, I will be reviewing open source projects on a live stream today at 2pm UK time (2.5 hours from now). 

Here is the YouTube live link https://www.youtube.com/watch?v=LyTUj6YQoBo

**Comment by flyingsonu122** [comment]
Awesome, I'm excited  🤩
