### ISSUE TITLE
How to get started in hackathons

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#32]
> I'd  like to know more about how to get started in hackathons, how to find a team, etc. I've never been to a hackathon. what are beginners projects i should try 

- how to get started in hackathons
- how to find a team
- project ideas

**Comment by eddiejaoude** [comment]
## how to get started in a hackathon

Hackathons seem scary, but they are not. Most hackathons are inclusive and want people from different backgrounds, experience, the more mix the better. The hackathons I have won are where we have had a mix of skills in the team, this allows for much better ideas. My biggest recommendation is to get involved and get started. I always learn so much at hackathons from the other attendees and mentors.

## how to find a team

Teams can be created before the event, but this usually means you are working with people you already know. One of the best things about hackathons is working with new and different people, this increases the learning. At hackathons they usually have time for people to make teams around similar ideas and challenges.

## project ideas

Usually once focused a similar challenge, people share project ideas, then when people start to gravitate to an idea, they break off into teams

---

This weekend is the Auth0 hackathon, apply and have fun https://auth0.devpost.com

**Comment by mohit01-beep** [comment]
I didn't make any application yet, but I want to try in it so what skills should I be more focused on ? So I'll be ready for a basic project for hackathons

**Comment by eddiejaoude** [comment]
It is not possible to predict what skills are needed, that is part of the fun. You can use skills you already have and also learn and use new skills.

When you join a team, usually people say what their skills are and what they want to learn. Doesn't matter what skills you have, its about adding value to the team and project, everyone can help push the project forward

**Comment by mohit01-beep** [comment]
Ok I'll start working on finding team now then, let's see how it goes for first time

**Comment by eddiejaoude** [comment]
I would not worry about trying to find a team before hand, in the agenda usually they allow for team building at the hackathon

**Comment by mohit01-beep** [comment]
Oh so I should focus on project ideas first?

**Comment by eddiejaoude** [comment]
Yes come up with some viable ideas, but don't get too attached to them, as they will probably change after you discuss with other attendees

**Comment by mohit01-beep** [comment]
yeah, i understand

**Comment by adityaoberai** [comment]
I have written an article on hackathon to-dos for folks who are beginning to (or have some experience) participating in hackathons as well :D

Do check it out here: [Hackathon To-Dos 101](https://blog.usejournal.com/hackathon-to-dos-101-272485ba4a8c?source=friends_link&sk=6a6060d91b47c669d9ed6ee09d4e5881) :)

**Comment by pranita28Dane** [comment]
Please invite me to the GitHub Community Organization

**Comment by eddiejaoude** [comment]
@pranita28Dane create an issue here and the bot will send you an invite https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&projects=&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization

You can read more about making the most out of the community and getting started with open source in our step by step guide https://github.com/EddieHubCommunity?view_as=public
