### ISSUE TITLE
Portfolio Review

### ISSUE THREAD

**Issue by created-by-varun** [EddieJaoudeCommunity/support#320]
Link to portfolio: https://its-varun.netlify.app/

[Above website was updated 5 months ago, looking to build something new, so feedback would be great]

**Comment by eddiejaoude** [comment]
Thank you. Can you also share a link to the open source GitHub repo for the portfolio please

**Comment by created-by-varun** [comment]
Sure, 
My github profile: https://github.com/created-by-varun/
Github repo of the portfolio website: https://github.com/created-by-varun/my-portfolio-v1

**Comment by eddiejaoude** [comment]
Thank you 👍 . I will take a look at your open source project in a live stream soon 🤓
