### ISSUE TITLE
It would be lovely to be invited to this GitHub Community Organisation

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieJaoudeCommunity/support#328]
Hi I'm an intermediate programmer, who's quite excited by open source and community-driven projects. in
I have intermediate knowledge of python, ruby, bash. I'm good at software troubleshooting, database creation and management(both sql and MongoDB), tkinter guis, DSA.
I am currently learning C. I am also experienced with Discord API
Feel free to ask me from email if you have some query- vyom.j@pm.me

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by Vyvy-vi** [comment]
Thank You!
