### ISSUE TITLE
I don't know what exactly visual studio is used for and which extensions?

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#33]
> I installed Visual Studio Code 2 months ago, and i tried to use it for 3-4 times, but i didn't know what exactly visual studio is used for? and  how to choose which extensions from market place should install?

- what is visual studio code used for
- which extensions should be installed

**Comment by eddiejaoude** [comment]
From their docs

> Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux. It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages (such as C++, C#, Java, Python, PHP, Go) and runtimes (such as .NET and Unity)

Basically it is a fancy text editor. It has things like auto complete, highlights errors, has a Git GUI built in, pairing with live code sharing... the list goes on. I highly recommend it for any developer.

Don't worry about what extensions to install until you need something - there are so many and so many that are similar (definitely worth looking at the reviews) 

Top extensions https://code.visualstudio.com/docs#top-extensions
Official website https://code.visualstudio.com

**Comment by mohit01-beep** [comment]
ok, maybe it'll help me
