### ISSUE TITLE
Project Review: CodeCapture

### ISSUE THREAD

**Issue by adityaoberai** [EddieJaoudeCommunity/support#331]
Hey @eddiejaoude 

My team would love to have our project [CodeCapture](http://code-capture.com) reviewed on a live stream.

The project's repository is available [here](https://github.com/code-capture/CodeCapture-PWA).

**Comment by eddiejaoude** [comment]
Thank you 👍 . I will take a look at your open source project in a live stream soon 🤓

**Comment by eddiejaoude** [comment]
Hi, I will be reviewing open source projects on a live stream today at 2pm UK time (2.5 hours from now). 

Here is the YouTube live link https://www.youtube.com/watch?v=LyTUj6YQoBo

**Comment by adityaoberai** [comment]
Awesome :D
