### ISSUE TITLE
Laravel - Target class [App\Listeners\LogVerifiedUser] does not exist.

### ISSUE THREAD

**Issue by natelloyd1** [EddieJaoudeCommunity/support#34]
Once an email address has been registered and the verification email is sent, I receive this error on the first click of 'verify email address'.  

If I click the 'verify email address' button _again_, it works. 

What might be causing that first error? 

Thanks. 

![Screenshot 2020-08-04 at 16 59 43](https://user-images.githubusercontent.com/57069051/89319481-1251ed00-d678-11ea-9d7c-13e54034dd36.png)

Here's a snippet of the error and the code where LogVerifiedUser is used.

![Screenshot 2020-08-04 at 17 28 47](https://user-images.githubusercontent.com/57069051/89319473-0d8d3900-d678-11ea-98c4-80ad8883750b.png)

**Comment by eddiejaoude** [comment]
From the error, it looks like the `LogVerifiedUser` class is not found. Does it exist?

**Comment by alrifay** [comment]
In [Laravel documentation](https://laravel.com/docs/7.x/verification#events) ```php App\Listeners\LogVerifiedUser``` is not a built in class it's an example for a listener.
Try `php artisan event:generate` to [generate the listener](https://laravel.com/docs/7.x/events#generating-events-and-listeners) for you.

**Comment by natelloyd1** [comment]
@alrifay thank you. In this case would I write `php artisan event:generate LogVerifiedUser `? Or just `php artisan event:generate`? 

I've tried `php artisan event:generate` which seemed to fix the 'verify email address' link on the email. However it's hanging on the register screen once I click register.

**Comment by stemount** [comment]
@natelloyd1 are you trying to create LogVerifiedUser and do something when an account is "verified"? if so:

```php artisan event:generate LogVerifiedUser``` will create that PHP file for you in App/Listeners/LogVerifiedUser.php with a class that you can then do things with.

**Comment by stemount** [comment]
@natelloyd1 

- [x] Completely half-read this issue
- [x] Actually know what that event:generate does.
- [x] Correct my mistakes ;)

What you want is a Listener as below.

```bash
githubrocks ➜ prototype git:(develop) php artisan make:listener MakeVerifiedUsersGreatAgain
Listener created successfully.
githubrocks ➜ prototype git:(develop) ✗ git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        app/Listeners/MakeVerifiedUsersGreatAgain.php

nothing added to commit but untracked files present (use "git add" to track)
githubrocks ➜ prototype git:(develop) ✗ 
```

**Comment by natelloyd1** [comment]
After a few tests that looks like it's fixed it!

So yes I (daringly) ran `php artisan make:listener MakeVerifiedUsersGreatAgain`

![Screenshot 2020-08-05 at 12 14 33](https://user-images.githubusercontent.com/57069051/89406539-3dd6e500-d715-11ea-9e7f-0b0cdf6b1669.png)
