### ISSUE TITLE
Review my GitHub Profile

### ISSUE THREAD

**Issue by AnkushSinghGandhi** [EddieJaoudeCommunity/support#343]
can you review my profile 
https://github.com/AnkushSinghGandhi

**Comment by eddiejaoude** [comment]
You did not pick the right template, so it might have got missed. I will add the `review` template label

**Comment by eddiejaoude** [comment]
Hi, I will be reviewing open source projects on a live stream today at 2pm UK time (2.5 hours from now). 

Here is the YouTube live link https://www.youtube.com/watch?v=LyTUj6YQoBo

**Comment by AnkushSinghGandhi** [comment]
thanx for the review eddie 😃😃
