### ISSUE TITLE
Please invite me to the GitHub Community Organisation

### ISSUE THREAD

**Issue by frankiefab100** [EddieJaoudeCommunity/support#350]
Please send me an invitation to join as member of Eddie Jaounde community.
I look forward to learning and collaborating with everyone.

**Comment by eddiejaoude** [comment]
I moved your other request from another repo to this `support` repo https://github.com/EddieJaoudeCommunity/support/issues/356

I will close this as it is a duplicate and the invitation has been sent already

**Comment by frankiefab100** [comment]
Alright, thanks
