### ISSUE TITLE
Review: Red Perfume (CSS Atomizer)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [EddieJaoudeCommunity/support#351]
This is a new open source project I started about a week ago. It's a build tool for automating the optimization of CSS.

* https://github.com/red-perfume/red-perfume

I'm looking for contributors. I've outlined issues of what work needs to be done, and prioritized the work based on what is most important to it being useful to others.

* https://github.com/red-perfume/red-perfume/projects/1

Issues have been given labels as well for what is blocked/blocking other issues, and what work would be good for those looking to contribute.

**Comment by eddiejaoude** [comment]
Hi, I will be reviewing open source projects on a live stream today at 2pm UK time (2.5 hours from now). 

Here is the YouTube live link https://www.youtube.com/watch?v=LyTUj6YQoBo
