### ISSUE TITLE
Project Review: Rotten Scripts

### ISSUE THREAD

**Issue by HarshCasper** [EddieJaoudeCommunity/support#352]
Hello @eddiejaoude 

I recently came across your Profile through a FreecodeCamp's Tutorial on Open-Source and was blown away with the clarity of thoughts and some of the new things that you introduced me to! 

I would love to have my Project [Rotten Scripts](https://github.com/HarshCasper/Rotten-Scripts) reviewed on a Live Stream. As a Project Admin, I have mentored Student Developers in contributing to this project as part of various Open Source Programs like Student Code-In, PClub Summer of Code, HakinCodes and recently the SLoP. 

Your suggestions and feedback on this Project will help me better to regulate it.

**Comment by eddiejaoude** [comment]
Hi, I will be reviewing open source projects on a live stream today at 2pm UK time (2.5 hours from now). 

Here is the YouTube live link https://www.youtube.com/watch?v=LyTUj6YQoBo
