### ISSUE TITLE
Project Review: Strawberry GraphQL

### ISSUE THREAD

**Issue by patrick91** [EddieJaoudeCommunity/support#358]
Hi there, I just started following you on youtube! I'd love to get a review on this project I'm working on: https://github.com/strawberry-graphql/strawberry

I've been trying to build a nice community around it and it seems to be going well, but would love to get some feedback from you <3

Thank you 🍓

**Comment by eddiejaoude** [comment]
Reviewed on a live stream, thank you for sharing 👍 https://www.youtube.com/watch?v=LyTUj6YQoBo
