### ISSUE TITLE
Please review my profile, project and portfolio 

### ISSUE THREAD

**Issue by dhausser** [EddieJaoudeCommunity/support#359]
Items we can review on a live stream:

- Profile: https://github.com/dhausser
- Project: https://github.com/dhausser/wanderlost
- Portfolio: https://www.davyhausser.com/showcase/

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Reviewed on a live stream, thank you for sharing 👍 https://www.youtube.com/watch?v=LyTUj6YQoBo
