### ISSUE TITLE
 Can you review my open source project  Scoop

### ISSUE THREAD

**Issue by SaiBalaji22** [EddieJaoudeCommunity/support#360]
I used this project https://github.com/SaiBalaji22/Scoop an iOS app for this year HacktoberFest. I submitted it to this repo https://github.com/dkhamsing/open-source-ios-apps as a Pull Request for  HacktoberFest.And it was accepted.Any suggestions to improve it :)

**Comment by eddiejaoude** [comment]
Thank you for submitting your project for review. I am recording a video now using your project as an example 🤓 

Your project looks good 👍 . My feedback for your open source project are:

- Add project description
- Add project topics
- Badge to be right at the top of the readme
- Under badge add your favourite screenshot to hook people to look further into your project
- Should `Scoop.xcodeproj` be committed?

**Comment by SaiBalaji22** [comment]
Thanks for your review 🙏 I will look into it and make necessary changes

**Comment by eddiejaoude** [comment]
You are welcome. The video will be out on my YouTube channel this week 🤓 

Btw I recommend also having a profile picture for your GitHub

**Comment by eddiejaoude** [comment]
Thank you for sharing it with us, the link to the YouTube video is https://youtu.be/nOZUP6Yf-jA
