### ISSUE TITLE
Project Review: simple sorting algorithms visualizer

### ISSUE THREAD

**Issue by LucasPilla** [EddieJaoudeCommunity/support#361]
I've been working in this project for a while, I would appreciate your feedback :)
Link for Repo: https://github.com/LucasPilla/Sorting-Algorithms-Visualizer

**Comment by eddiejaoude** [comment]
Your project looks great 👍 

I am using it for my next video 🤓 

My only feedback would be to add a Code of Conduct and a Contributors file

**Comment by LucasPilla** [comment]
Thank you for reviewing my project. :smile:

**Comment by eddiejaoude** [comment]
Thank you for sharing it with us, the link to the YouTube video is https://youtu.be/nOZUP6Yf-jA
