### ISSUE TITLE
 Project Review: CodeTreats

### ISSUE THREAD

**Issue by adarshaacharya** [EddieJaoudeCommunity/support#363]
I've recently done open source project named CodeTreats - an online code editor/ collaborative tool. 

https://github.com/adarshaacharya/CodeTreats

I would love to get feedback from you. :)

**Comment by adarshaacharya** [comment]
I've not experience inmaintaining Open source project & my project is not that popular so waiting for some tips from you :)

**Comment by eddiejaoude** [comment]
@adarshaacharya any reason why this was closed? I don't think I got round to reviewing it in my last live stream so I would like to keep it open for my next live stream

**Comment by adarshaacharya** [comment]
@eddiejaoude I thought my project didn't fulfill criteria to be reviewed so.. :) 

Thank you for information.

**Comment by eddiejaoude** [comment]
No not at all - there is only 1 criteria, open source 🤓 

I will collect these projects for the next live stream. Thank you for sharing your project 👍

**Comment by eddiejaoude** [comment]
Project looks great 👍  - I am using it for my next YouTube video 🤓 

My feedback suggestions:

- Create a release, even if a beta / prototype
- What minimum version of node is required 
- Use issues more, and I recommend with the project board
- Add a Code of Conduct
- Add a Contributing file

**Comment by eddiejaoude** [comment]
Thank you for sharing it with us, the link to the YouTube video is https://youtu.be/nOZUP6Yf-jA

**Comment by adarshaacharya** [comment]
Thank you for reviewing project. Will add the above points :)
