### ISSUE TITLE
Review my open source link

### ISSUE THREAD

**Issue by mizan4392** [EddieJaoudeCommunity/support#370]
Items we can review on a live stream:

- GitHub profile
- Open source project
- Portfolio

**Project Link**: https://github.com/mizan4392/lightsout

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 - this will be reviewed in a live stream soon

**Comment by mizan4392** [comment]
Thank you vary much for you tips and all help for open source contribute guid

**Comment by eddiejaoude** [comment]
Your project looks good 👍  - I am reviewing it for my next video I am recording now 🤓 

Some feedback on your project:
- Add topics and the url to the deployed project at the top right with the description 
- Readme needs more information, for example what are the requirements, screenshot etc
- Add a Code of Conduct
- Add a license

**Comment by eddiejaoude** [comment]
Thank you for sharing it with us, the link to the YouTube video is https://youtu.be/nOZUP6Yf-jA
