### ISSUE TITLE
Adding my open source project link to get a review.

### ISSUE THREAD

**Issue by ChoukseyKhushbu** [EddieJaoudeCommunity/support#371]
- [Open Source Project](https://github.com/ChoukseyKhushbu/gitzilla)

PS: I am not working on this project for quite a few days due to my college and volunteering works but a lot of work is under development. Have to learn a lot more and implement it in this project.
I would be highly grateful if my project is reviewed by you.

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . I will review in a live stream soon 🤓

**Comment by eddiejaoude** [comment]
Looks great 👍 

Recording a YouTube video to come out this week, here are my suggestions from the video:

- screenshot in readme 
- code of conduct file
- contributor file
- issue and pull request template

**Comment by eddiejaoude** [comment]
Thank you again for sharing your open source project, I think you saw the video already, but just to be complete, I will include a link here and close the issue 🤓  https://www.youtube.com/watch?v=N34ViIk0C0k
