### ISSUE TITLE
how to contribute or what prerequisites require to get involve more

### ISSUE THREAD

**Issue by kruthikahm2000** [EddieJaoudeCommunity/support#378]
As I'm new to this contribution dono how to add up the value, as of now I'm only good at front-end and python one who is in the entry level of professional degree so please guide me how to contribute or what prerequisites require to get involve more?!

**Comment by eddiejaoude** [comment]
hi @kruthikahm2000 , your fresh pair of eyes to any project can help lower the barrier to entry for the project and make it more inclusive. Find a project you like the look of and get involved in the discussions in the Issues and Pull Requests. Then you will more easily find ways to get involved in contributing on the technical level. My biggest advice is to start by getting involved in the conversation. You are here which is a good start 👍

**Comment by eddiejaoude** [comment]
I will move the title into the description because it is 4 lines and it should only be 1 line

**Comment by eddiejaoude** [comment]
I will close for now. @kruthikahm2000 feel free to start a another discussion in the future
