### ISSUE TITLE
Please invite me to the GitHub Community Organisation

### ISSUE THREAD

**Issue by harshilparmar** [EddieJaoudeCommunity/support#385]
@eddiejaoude I would love to join your community ✌️ 
I got to know about you by this [youtube video](https://www.youtube.com/watch?v=yzeVMecydCE).You have done a great job 💯 .
I have started open source for past six month till now I have done some good first contributions and some others.
Now I want to know how to contribute to big project like react.I got confused because codebase is huge.I know it takes time,but how to do that ? **Thanks** 🙇 

Thanks!!!

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
