### ISSUE TITLE
Add links to "issue" and "discussion" in README

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/support#388]
These sections could do with links to make it easier for the user

<img width="1170" alt="Screenshot 2020-10-24 at 10 14 11" src="https://user-images.githubusercontent.com/624760/97078149-e0e71e80-15e1-11eb-86fe-742fc4efa902.png">

**Comment by VictoryWekwa** [comment]
Hello, please can this be assigned to me?
Thank you.

**Comment by eddiejaoude** [comment]
Sure @VictoryWekwa 👍

**Comment by VictoryWekwa** [comment]
Hello @eddiejaoude I just created a PR kindly review. Thank you
