### ISSUE TITLE
General Template Repository

### ISSUE THREAD

**Issue by MallikarjunHt** [EddieJaoudeCommunity/support#389]
**Description**

Love to have a Template Repository with cool action and CoC.
* Welcome action
* Upstream sync
* Stall issue not
* Code of conduct
* Issues template 
* Pull request temple
* Verbal (A*) can't remember the name but it would be great to have a temple repository so all Repository can be consistent will action and code of conduct.

Thanks and happy to discuss on this ❤️

**Comment by eddiejaoude** [comment]
Good idea @MallikarjunHt I think it was spoken about before, but this is the nudge I need to create the repo, then people can start contributing to it 👍 

We can raise specific issues on the `template` repo for each item, for example `GitHub Action to do ... `

https://github.com/EddieJaoudeCommunity/template

**Comment by eddiejaoude** [comment]
@MallikarjunHt this has been started. I think we should close this issue and then create an Issue on the `template` repo for each time you mentioned above. What do you think?

**Comment by MallikarjunHt** [comment]
sure, its a good idea
