### ISSUE TITLE
Take inspiration from similar projects

### ISSUE THREAD

**Issue by stemount** [EddieJaoudeCommunity/support#4]
Starting this off with @praveenscience's great starting off inspiration... but any profiles!
https://github.com/praveenscience/ama

**Comment by stemount** [comment]
@eddiejaoude This has actually definitely superseded the root idea I had of the repository and we now have GitHub discussions.

The new "remix" of the root idea for the support repo is working really well so this is now a closed ticket.

**Comment by eddiejaoude** [comment]
Sounds good 👍 . I think we need to encourage more discussion on GitHub Discussions and then if any actions are to be taken we can create a GitHub Issue for it.
