### ISSUE TITLE
Updating a section in the README using "readme-box" in a GitHub Action

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/support#40]
**Description**

I would like to update the a section in the README using [readme-box](https://github.com/jasonetco/readme-box). I get an error `##[error]Contents do not contain start/end comments for section "data-section"`, the section does exist, I must be missing something else.

Here is my code to update the README:

```js
await readmeBox.updateSection(content, {
            owner: process.env.GITHUB_REPOSITORY.split('/')[0],
            repo: process.env.GITHUB_REPOSITORY.split('/')[1],
            token: githubToken,
            section: 'data-section',
});
```

Here is the README code:

```markdown
<!--START_SECTION:data-section-->
<!--END_SECTION:data-section-->
```

GitHub Action job run https://github.com/EddieJaoudeCommunity/awesome-github-profiles/runs/950486163?check_suite_focus=true

**Stack**

GitHub Action with NodeJS

**Comment by JasonEtco** [comment]
`ReadmeBox.updateSection` gets the README contents from the default branch via API requests, not by reading the file within Actions:

https://github.com/JasonEtco/readme-box/blob/601b520c34c8292ef9c33afcbb0a7ddba7412a4b/src/index.ts#L44-L45

So you'd need to merge the addition of those comments before this Action works 😬 I realize that's a little weird - so you can use the various helper methods instead:

```js
const oldContent = fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'README.md'))
const box = new ReadmeBox()
const replacedContents = box.replaceSection({
  section: 'data-section',
  oldContent,
  newContent: 'some new stuff'
})
```

**Comment by eddiejaoude** [comment]
Awesome, thank you 👍 .

Is the `token` no longer needed?

**Comment by JasonEtco** [comment]
Yep, if you're not making API calls you don't need it as an option in the constructor! If you want to use `ReadmeBox#updateReadme` you'd need it though, up to how you actually update the file contents in Git.

**Comment by eddiejaoude** [comment]
I changed direction, but now I came back 😂 . I thought I could use the `branch` option in `updateSection`. What do you think?

**Comment by eddiejaoude** [comment]
Oh although `branch` is part of `ReadmeBoxOpts`, when `updateSection` uses `updateReadme` it has the branch hardcoded `branch: 'master'`, so that won't work 🤔

**Comment by eddiejaoude** [comment]
I will raise you a PR 🤓

**Comment by eddiejaoude** [comment]
I test the PR I raised from my fork in my Github Action and it worked 🎉
