### ISSUE TITLE
Please Review my project and profile

### ISSUE THREAD

**Issue by akshitagupta15june** [EddieJaoudeCommunity/support#402]
Items we can review on a live stream:

- GitHub profile https://github.com/akshitagupta15june
- Open source project  : https://github.com/akshitagupta15june/vehicle_speed_estimator

- Portfolio  https://github.com/akshitagupta15june/akshitagupta15june

please review my project of lane detection using openCV.

**Comment by akshitagupta15june** [comment]
@eddiejaoude

**Comment by eddiejaoude** [comment]
Thank you @akshitagupta15june for sharing your open source projects for review. I will review these on a live stream or video on my YouTube channel soon

**Comment by akshitagupta15june** [comment]
Thankyou so much

**Comment by eddiejaoude** [comment]
## Feedback for your profile

- looks great 👍 
- missing image on the right side
- suggestion using your linkedin photo on twitter and GitHub too - it will look more professional 

## Feedback for vehicle_speed_estimator

- great animated image
- remove and ignore `.idea` folder
- tech requirements section would be useful
- quickstart - how to install and run the project
- add code of conduct
- add license
- add contributing file

**Comment by akshitagupta15june** [comment]
Thank-you so much @eddiejaoude

**Comment by eddiejaoude** [comment]
Thank you again for sharing your open source project, I think you saw the video already, but just to be complete, I will include a link here and close the issue 🤓  https://www.youtube.com/watch?v=N34ViIk0C0k
