### ISSUE TITLE
Review my shark quiz game

### ISSUE THREAD

**Issue by vinzvinci98** [EddieJaoudeCommunity/support#403]
Hello, please review and give me some suggestions to improve this 2D game ^_^ Thank you

https://github.com/vinzvinci98/Shark-Quiz

**Comment by eddiejaoude** [comment]
Thank you for sharing, I am creating a video for my YouTube channel now, here are my thoughts, video to come out later this week:

- great animated gif in the readme 👍 
- add code of conduct
- add contributing file
- use issues more
- should `nbproject` be submitted?
- should the repo be a `template` repo?

**Comment by vinzvinci98** [comment]
Thank you so much, I am making some changes right now. 

✔️ added code of conduct
✔️ added contributing file
✔️ uncommit _nbproject_
✔️ removed template repo 

**I will improve this project later**

**Comment by eddiejaoude** [comment]
Thank you again for sharing your open source project, I think you saw the video already, but just to be complete, I will include a link here and close the issue 🤓 https://www.youtube.com/watch?v=N34ViIk0C0k
