### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by EugeneGohh** [EddieJaoudeCommunity/support#405]
May i know can i contribute on GitHub and in your organization?

**Comment by eddiejaoude** [comment]
Of course 👍 - I see you are already in our organisation 🤓

**Comment by EugeneGohh** [comment]
How can i get started to contribute ? I am a beginner new to this.

**Comment by eddiejaoude** [comment]
I have many videos on this, here is a recent video which mentions hacktoberfest a lot, which has now finished, but the principles are the same. Have a watch and we can take our discussion from there https://www.youtube.com/watch?v=tjH6txTiC6E 

Did you join our Discord? Lots of people in there to give ideas and tips too from different technologies 🤓

**Comment by EugeneGohh** [comment]
Yes I did joined your Discord server.Thank you for the video just subscribed to your channel and willing to learn Open Source from you by the way I just found you on FreeCodeCamp Open Source Video too.

**Comment by eddiejaoude** [comment]
Great 👍 , say hi in the Discord, and ask about getting involved, lots of people will help 🤓 .

Thank you for subscribing to my channel. Let me know what type of videos you would like to see 🎥
