### ISSUE TITLE
How to built a README more creative and best(from basics to advance). 

### ISSUE THREAD

**Issue by kruthikahm2000** [EddieJaoudeCommunity/support#406]
**Description**

A brief description of the question or issue, also include what you tried and what didn't work:

**Stack**

Project stack or language (eg. Frontend):

**Working Environment**

Operating System (eg Linux):

Browser (eg. Chrome):

Device (eg. Laptop or Phone):

**Screenshots**

Please add a screenshot if applicable

[Optional] **Additional Context**

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Great questions @kruthikahm2000 👍 . This might be better done in the Discussions section. Do you mind closing this and starting a discussion here https://github.com/EddieJaoudeCommunity/support/discussions

**Comment by eddiejaoude** [comment]
Discussion created, so I will close this issue https://github.com/EddieJaoudeCommunity/support/discussions/412
