### ISSUE TITLE
Maintainers Required: TailwindCSS Classnames for React and friends.

### ISSUE THREAD

**Issue by stemount** [EddieJaoudeCommunity/support#407]
## This project is looking for maintainers

https://github.com/muhammadsammy/tailwindcss-classnames/issues/62#issuecomment-723036942

---

Bigging up @muhammadsammy's work:

**What I'd like to know:**

1. Does this only work with React?
2. Any idea of support in WebStorm/PHPStorm et al?

Items we can review on a live stream:

**- GitHub profile**

https://github.com/muhammadsammy

**- Open source project**

https://github.com/muhammadsammy/tailwindcss-classnames
https://www.npmjs.com/package/tailwindcss-classnames

**- Portfolio**

Muhammad can add their if he see's fit

---

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for sharing @stemount 👍

**Comment by muhammadsammy** [comment]
First of all, I want to thank @eddiejaoude for creating this community and supporting open source!

<hr />

@stemount thanks for sharing!

> 1. Does this only work with React?
> 

It can be used with other frameworks too or with vanilla typescript.

> 2. Any idea of support in WebStorm/PHPStorm et al?
> 
The project adds typescript support through generating types for tailwindcss classes and using the [classnames library](https://www.npmjs.com/package/classnames) for composing these classes, so, it should have the same support for all IDEs that support typescript.

> **- Portfolio**
> 
> Muhammad can add their if he see's fit
>
My Linkedin account: https://www.linkedin.com/in/muhammad-sammy.

Thanks again for sharing this and helping out!

**Comment by eddiejaoude** [comment]
This project looks epic!! I am including it in my YouTube video for open source reviews and I hope it gets more traction and contributors.

@muhammadsammy you have created a really great open source project, my open source suggestions were so minor, and I learnt a lot looking at your project - I look forward to sharing it with my community 👍 

Thanks again @stemount for sharing 🤓

**Comment by mikeysan** [comment]
What are the requirements of becoming a maintainer for the project? I would volunteer to be one, but I don't know tailwindcss, JS or TS.

**Comment by muhammadsammy** [comment]
That's very nice, @eddiejaoude. I can't thank you enough! 
I'm really excited to watch your videos and learn from them and the amazing community.
Also, @christianalfoni was actually the one who came up with the idea and the project wouldn't exist without him.
Thanks a lot!

**Comment by muhammadsammy** [comment]
> What are the requirements of becoming a maintainer for the project? I would volunteer to be one, but I don't know tailwindcss, JS or TS.
>

@mikeysan Thanks for your interest in helping!
I believe you should to know JS then picking up TS would be easy.

You are very welcome to contribute to the project. I would be happy to get help from the community!
Also, the codebase is not well documented which is not very welcoming for newcomers to the project, so when I have time, I will document it to make it easier to reason about!

**Comment by eddiejaoude** [comment]
The video of me reviewing this project is being edited tomorrow and coming out later this week. During the review I raised this [issue](https://github.com/muhammadsammy/tailwindcss-classnames/issues/65), but I actually want to solve that issue of adding some of the commands to a GitHub Action on another dedicated video on how to add value to the community 🤓 

I am putting here as a note for myself not to forget 😂

**Comment by eddiejaoude** [comment]
Video is live https://www.youtube.com/watch?v=braWUyC77z4&feature=youtu.be

**Comment by muhammadsammy** [comment]
I appreciate the very useful feedback. So thankful!
