### ISSUE TITLE
Typo in community question

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/support#41]
Initial found https://github.com/EddieJaoudeCommunity/support/issues/2#issuecomment-669503621 , thanks @stemount 

![image](https://user-images.githubusercontent.com/150512/89463013-2ffd8000-d766-11ea-8f04-b6317575af08.png)

**Comment by Ruth-ikegah** [comment]
Um @eddiejaoude can I sort this out, wanna use it as a written guide on my next blog post, Beginner's guide to open source. It's a simple attractive issue to introduce beginners to

**Comment by eddiejaoude** [comment]
Sure, awesome 👍 . I have assigned it to you 🤓

**Comment by eddiejaoude** [comment]
Fixed here https://github.com/EddieJaoudeCommunity/support/pull/54
