### ISSUE TITLE
Issue for review for my Todo App

### ISSUE THREAD

**Issue by max-programming** [EddieJaoudeCommunity/support#419]
Items we can review on a live stream:

- GitHub profile - [Max Programming](https://github.com/max-programming)
- Open source project - [Max Todos](https://github.com/max-programming/max-todos)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for submitting @max-programming 👍

**Comment by eddiejaoude** [comment]
@max-programming looks great 👍 , I reviewed it for a YouTube video, here are my thoughts ...

- is the `.vscode` folder needed?
- create a release
- screenshot in the README (or animated gif)
- use GitHub Action for the `build` command in `package.json` 
- Add Code of Conduct
- Add license

**Comment by max-programming** [comment]
Thank you so much @eddiejaoude. I'll apply changes for all of these. These are very important things I did not know

**Comment by eddiejaoude** [comment]
You are welcome 🤓 - I miss lots of things on my projects, so do not worry, it happens to everyone 🤦‍♂️

**Comment by mikeysan** [comment]
> 
> 
> @max-programming looks great 👍 , I reviewed it for a YouTube video, here are my thoughts ...
> 
>     * is the `.vscode` folder needed?
> 
>     * create a release
> 
>     * screenshot in the README (or animated gif)
> 
>     * use GitHub Action for the `build` command in `package.json`
> 
>     * Add Code of Conduct
> 
>     * Add license

.vscode folder can be added to the .gitignore file. That's what I do with mine so it doesn't get uploaded.

**Comment by Vyvy-vi** [comment]
> What is the purpose or need of adding a LICENSE?
(*this is how I understand it, but I'm sure someone else could explain this better)
Generally adding a license to your project increases usability for other developers.
Unlicensed software might get restrictive licenses later on and that might lead to legal issues...

A LICENSE acts as a RULE-BOOK that governs how other people could use your software.
For example: 
 - You want your software to be useable by anyone in any form, but you want to firmly reassure that there are no liabilities or warranties that come with the software, but want the users to withhold the same LICENSE. In this case you could use MIT License
 - You want a copyleft license(no close sourcing of your code, but use in any form):
 GNU GPLv3 or GPLv2
 - You want a super-permisive, no liability, no clause license:
 The Unlicense
 - Apache License: similar to GPLv3, but restrictive in copied use of trademarks in the code
 Here's a great resource on LICENSEs: https://choosealicense.com/
 
 Here's what would happen if you don't have a license:
 https://choosealicense.com/no-permission/

**Comment by max-programming** [comment]
> > 
> > 
> > @max-programming looks great 👍 , I reviewed it for a YouTube video, here are my thoughts ...
> > 
> >     * is the `.vscode` folder needed?
> > 
> >     * create a release
> > 
> >     * screenshot in the README (or animated gif)
> > 
> >     * use GitHub Action for the `build` command in `package.json`
> > 
> >     * Add Code of Conduct
> > 
> >     * Add license
> 
> .vscode folder can be added to the .gitignore file. That's what I do with mine so it doesn't get uploaded. 

I upload it for custom settings like formatting the file, etc

**Comment by max-programming** [comment]
> > What is the purpose or need of adding a LICENSE?
> 
> 
> (*this is how I understand it, but I'm sure someone else could explain this better)
> Generally adding a license to your project increases usability for other developers.
> Unlicensed software might get restrictive licenses later on and that might lead to legal issues...
> 
> A LICENSE acts as a RULE-BOOK that governs how other people could use your software.
> For example: 
>  - You want your software to be useable by anyone in any form, but you want to firmly reassure that there are no liabilities or warranties that come with the software, but want the users to withhold the same LICENSE. In this case you could use MIT License
>  - You want a copyleft license(no close sourcing of your code, but use in any form):
>  GNU GPLv3 or GPLv2
>  - You want a super-permisive, no liability, no clause license:
>  The Unlicense
>  - Apache License: similar to GPLv3, but restrictive in copied use of trademarks in the code
>  Here's a great resource on LICENSEs: https://choosealicense.com/
>  
>  Here's what would happen if you don't have a license:
>  https://choosealicense.com/no-permission/

Thanks for your kind reply. Adding a license is not a big deal

**Comment by Vyvy-vi** [comment]
(Also, not having a LICENSE means that editing your code might breach the intellectual property copyright or something, resulting in less contributers)

**Comment by eddiejaoude** [comment]
Video is live https://www.youtube.com/watch?v=braWUyC77z4&feature=youtu.be

**Comment by max-programming** [comment]
Thank you so much @eddiejaoude
