### ISSUE TITLE
I want to make a customised GitHub Profile, how can i make one? 

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#42]
**Description**

A brief description of the question or issue:

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Comminity [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
1. Create a repo with the same name as your user, in your case `mohit01-beep`
2. Then update the `README.md` to customise your GitHub profile 

Here are some examples for inspiration https://github.com/EddieJaoudeCommunity/awesome-github-profiles *(note: you can look at their raw README files to see how they did it)*

**Comment by mohit01-beep** [comment]
I still didn't get it when i opened the link of awesome GitHub profiles
It says in steps that you have to take a screenshot of customized GitHub Profile Page,
 But i was asking how to make that one 
And after i clicked at some of their example for inspiration of GitHub Profile
it's just Screenshot of them- no code, no text  
So it didn't help me much
can you tell me where is the code to make like them so i can experiment with it and see how my profile will look

**Comment by eddiejaoude** [comment]
I think you are confusing that repo with how to customise your page.

The instructions on the link are how to add someones customised profile to that repo for displaying in the readme, not how to customise your GitHub profile.

If you want to customise your github profile, which I think  you do as it is not customised yet, then you need to follow these steps in the above comment https://github.com/EddieJaoudeCommunity/support/issues/42#issuecomment-669892859

If you want inspiration from the `awesome-github-profiles` repo, then click on the the users name not the image and view their `README.md` file (raw), to see how they have achieved it.

**Comment by mohit01-beep** [comment]
yeah i found how to edit my README.md file thanks for helping @eddiejaoude

**Comment by eddiejaoude** [comment]
Ok great 👍
