### ISSUE TITLE
[Project Review]: TearDrops(Discord-Bot: discord.py, python)

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieJaoudeCommunity/support#429]
Items we can review on a live stream:

- Open source project

#### brief description:
A discord bot wrapped around the theme of tears and crying using the discord.py module. In concept, the idea is absurd but that's more of a reason to make this. :) The bot uses tears as an economy and you can "cry" to get daily credit tears.
#### project status:
still in progress(v0.1 will be launched in a few days)
#### Project Link:
https://github.com/Vyvy-vi/TearDrops
#### Additional Context:
![Screenshot 2020-11-14 at 11 21 18 PM](https://user-images.githubusercontent.com/62864373/99153692-1e663580-26d0-11eb-8072-bb590620d7d5.png)

(This is my first large-scale opensource repo and a first-timer maintainer task)
I follow all-contributors, so open an idea/suggestion in an issue after reviews : ) 
All suggestions, criticisms, etc. would be completely welcome... 👍

**Comment by eddiejaoude** [comment]
Thanks for sharing 👍

**Comment by Vyvy-vi** [comment]
(Is this a nudge from stale-bot to Eddie, for reviewing my bot)

**Comment by Vyvy-vi** [comment]
stalebot :C

**Comment by BOLT04** [comment]
Has your project been reviewed @Vyvy-vi ? If not I think we should keep this open and ignore the fact that the bot closed it 😃

Here are some comments from what I saw in your project:
- Awesome display of organization and using standard names for issues:
![imagem](https://user-images.githubusercontent.com/18630253/105637177-00514a00-5e64-11eb-8861-430fc76ceaf6.png)
- I see the latest release is v1.0 but there are some notes in the docs that point to v0.1 [here](https://github.com/Vyvy-vi/TearDrops#how-to-run-the-bot-on-your-own-server)
![imagem](https://user-images.githubusercontent.com/18630253/105637217-31ca1580-5e64-11eb-936e-400a2c3da7ac.png)
- small typo on the `README` like "refere" [here](https://github.com/Vyvy-vi/TearDrops#how-to-report-a-bug)

Other than that, pretty cool project 👍

**Comment by Vyvy-vi** [comment]
Thanks for the feedback-!
I'll make the fixes

My project hasn't been reviewed...

**Comment by Vyvy-vi** [comment]
thank @BOLT04  :)

**Comment by eddiejaoude** [comment]
Reviewed as part of this live stream https://youtu.be/_JjV9n-G-p0

Feedback / suggestions 
- Looked really good and inclusive 
- PR template would be useful even if simple
- Maybe move "Requirements" section to the top
- Fix failing GitHub Actions

**Comment by Vyvy-vi** [comment]
Thanks for the review and suggestion-! 🙃
