### ISSUE TITLE
NXDOMAIN when creating a normal subdomain / A record below a CNAME record

### ISSUE THREAD

**Issue by TECHNOFAB11** [EddieJaoudeCommunity/support#43]
So i use CNAME to forward bot.abc.de to my local server where my app is running. Now i want to add docs under docs.bot.abc.de. Problem is, that LetsEncrypt and https://check-your-website.server-daten.de/?q=docs.bot.abc.de for example say that the DNS thing is invalid. I though CNAME just counts for exactly that URL? Or does it also forward sub subdomains? :smile:
LetsEncrypt error if needed: 

```
Invalid response from https://acme-v02.api.letsencrypt.org/acme/authz-v3/XXXXXXXX.
Details:
Type: urn:ietf:params:acme:error:dns
Status: 400
Detail: DNS problem: NXDOMAIN looking up A for docs.bot.abc.de - check that a DNS record exists for this domain
```

I hope these ids are no sensitive data :stuck_out_tongue: meh, better safe than sorry

Theoretically i shouldnt need it as my hoster has rules for * which point to the IP of the webserver. So i hope this subdomain goes there too, just like the many others i have lol :smile:

**Comment by eddiejaoude** [comment]
From [Discord](https://discord.com/invite/jZQs6Wu)...

@AllanRegush 
> For sub domains I’ve had to make another entry in my dns panel. Although it’s been awhile since I’ve set up a domain.

@TECHNOFAB11 
```
; <<>> DiG 9.11.2 <<>> docs.bot.abc.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 8590
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;docs.bot.abc.de.         IN      A

;; AUTHORITY SECTION:
abc.de.           2368    IN      SOA     root-dns.netcup.net. dnsadmin.netcup.net. 2020070815 28800 7200 1209600 86400

;; Query time: 2 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Thu Aug 06 19:20:42 CEST 2020
;; MSG SIZE  rcvd: 114
```

> Thats the dig output. I dont really use this tool, why does it say my router's IP behind SERVER? nvm it always does that

@AllanRegush 
> I think your cert only covers the root.

@TECHNOFAB11 
> It works with other subdomains (even sub sub sub subdomains etc.) so it should work, right?

@AllanRegush 
> Same server?

@TECHNOFAB11 
> The only difference is the CNAME "in between" the lowest subdomain and domain. But as my CNAME is bot.technofab.de and not *bot.abc.de it should ignore everything except bot.abc.de
https://holy.heck.this.works.abc.de/
Btw, this works
Just created that one
