### ISSUE TITLE
How to change  github email

### ISSUE THREAD

**Issue by gaushikmr** [EddieJaoudeCommunity/support#44]

**Comment by eddiejaoude** [comment]
What have you tried from their docs?  https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-primary-email-address

**Comment by gaushikmr** [comment]
@eddiejaoude its cleared no issues Thanks.

**Comment by eddiejaoude** [comment]
Maybe you want to share how you did it to help other people 😉

**Comment by gaushikmr** [comment]
@ok but I am facing an issue My commits are changed

**Comment by gaushikmr** [comment]
I followed this link: https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-primary-email-address

**Comment by eddiejaoude** [comment]
> I am facing an issue My commits are changed

Not sure what you mean. Maybe you would like to share some more information on what your issue?

**Comment by gaushikmr** [comment]
@I deleted the email which I gave first so the commits made using that email are gone when I deleted and when I added it again all my commits are back.

**Comment by eddiejaoude** [comment]
`git` commits are associated by a user and email, if you change your email on GitHub it does not change any historic commits or any commits done via the git cli if that user doesn't match the GitHub 

Here is a link to the GitHub docs to update your git cli user https://docs.github.com/en/github/using-git/setting-your-username-in-git

**Comment by stemount** [comment]
> `git` commits are associated by a user and email, if you change your email on GitHub it does not change any historic commits or any commits done via the git cli if that user doesn't match the GitHub
> 
> Here is a link to the GitHub docs to update your git cli user https://docs.github.com/en/github/using-git/setting-your-username-in-git

@gaushikmr Changing your Git Global settings to match will help if you use HTTPS as the remote. If you use Git with the SSH protocol, your SSH key may correct the email.

Closing as answered.
