### ISSUE TITLE
Add Channel Descriptions to Discord 

### ISSUE THREAD

**Issue by GoluffyxD** [EddieJaoudeCommunity/support#440]
**Description**

Addition of Channel Descriptions on Discord can be useful.
Suggested by @Vyvy-vi .

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by Vyvy-vi** [comment]
hmm this seems to be a needed thing
Imho, people(including me) are often confused which message should go where

**Comment by nhcarrigan** [comment]
To be completely honest, I also feel that the channels could be consolidated. There are currently a *lot*, and many of them are silent.

**Comment by BOLT04** [comment]
This is a good idea @GoluffyxD and @Vyvy-vi 👍.
I've seen some Discord servers having a `readme` channel or something similar to explain rules and other stuff: 
![imagem](https://user-images.githubusercontent.com/18630253/99878643-f2cada00-2bfe-11eb-8ece-8da2c7774e3f.png)

Maybe we could do the same and put the channel descriptions there. Or do you suggest putting it on the support repo's `README`?

**Comment by Vyvy-vi** [comment]
(why not both?)
Sync the repo readme, with the discord server channel using eddiebot.
(messages are added in some format, and when run, eddiebot reads file data, to check if new entry exists and posts a message in the channel)

**Comment by BOLT04** [comment]
yes we could have it on both places @Vyvy-vi, but maybe that would be a more complex solution.
For now, I think we can simplify this and just ask @eddiejaoude to add a channel that has channel descriptions and other important information when joining the Discord server.

@EddieJaoudeCommunity/coreteam what does everyone think?

**Comment by Vyvy-vi** [comment]
Here's a sort of template regarding the descriptions(might make eddie's work easier 🤓 ):
(from my perspective)
```md
**Welcome to the EddieJaoudeCommunity Discord server!**

We believe Open Source is for everyone, yes you!
OPEN SOURCE is NOT about code, it is about people and collaboration
We are invested in getting you those green squares 🟩  on GitHub! Contributing to Open Source Software (OSS) is a great way for you to learn, work with different people and also network. 

#### Please try to adhere by our Code Of Coduct(COC):
We as members, contributors, and leaders pledge to make participation in our
community a harassment-free experience for everyone, regardless of age, body
size, visible or invisible disability, ethnicity, sex characteristics, gender
identity and expression, level of experience, education, socio-economic status,
nationality, personal appearance, race, religion, or sexual identity
and orientation.
We pledge to act and interact in ways that contribute to an open, welcoming,
diverse, inclusive, and healthy community.
The following are the guidelines regarding chat on the discord server:
- Using welcoming and inclusive language
- Being respectful of differing viewpoints and experiences
- Gracefully accepting constructive criticism
- Focusing on what is best for the community
- Showing empathy towards other community members
Full details on- https://github.com/EddieJaoudeCommunity/support/blob/main/CODE_OF_CONDUCT.md

#### Enforcement:
Instances of abusive, harassing or otherwise, unacceptable behaviour may be reported by contacting the project team at eddie@jaoudestudios.com. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.
```

**Comment by BOLT04** [comment]
@Vyvy-vi that is a very good start 👍. If @eddiejaoude agrees to create that `readme` channel or something else, we could make an announcement on the `announcements` channel saying this was created for this purpose...but the bot picks up and announces it on the general channel already 😅

**Comment by eddiejaoude** [comment]
Oh nice, great team work 💪 

So many good ideas, let me get started on those 🤓 

Actions:
- Readonly channel called `README` with the info from @Vyvy-vi 
- I think we should add the text to the `support` repo so people can make PRs to it and I can copy and paste it into the channel

Did I miss anything? We could automate it with EddieBot in the future, a new issue could be created for this

**Comment by eddiejaoude** [comment]
It should be readonly

<img width="1500" alt="Screenshot 2020-11-24 at 03 05 08" src="https://user-images.githubusercontent.com/624760/100041748-e5317200-2e01-11eb-86dd-db0f2582a024.png">

**Comment by eddiejaoude** [comment]
I updated the text slightly, if would like to can create a PR with a file `discord-readme.md` in this repo with the text from the #readme channel, we can use that as a starting point and make changes from there 🤓 

Then I think we can close this issue afterwards?
