### ISSUE TITLE
Please Review my PYPI Python Package

### ISSUE THREAD

**Issue by janaSunrise** [EddieJaoudeCommunity/support#446]
Items we can review on a live stream:

- Open source project

It is a Python Package specially make for minecrafteers, and Bot developer to extract the stats, and display to the people.
It's not something really unique, But I keep it different by Using really good docstrings, and suggested in pep along with modularity in code, allowing better control over the objects, and accessing the data, and also showing them, It also supports various paradigms in Code.

Status: Alpha
Latest release : 0.0.7

New release within a week, Major fixes are being worked on in a single or 2 or 3 commits.

Link: https://github.com/janaSunrise/HypixelIO

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thank you for sharing 👍 . It is the queue to get reviewed 🤓

**Comment by Vyvy-vi** [comment]
Oh looks good 👍  (I was looking into fetching data from hypixel using `requests`, though this might make my work easier 🤔 )
It would be nice if we have issues, a more detailed README(maybe just add a link to the `docs` folder), a full fledged-release(all the current tags seem to be pre-release), display package on the repo page

**Comment by janaSunrise** [comment]
Yeah, I've been trying a lot to make things, I need some time, as I am the lone contributor 😅 So, Pardon me if there are no external docs, or tests, or something is missing. I'll add them to the project board. And Also, I've been doing a lot of Fixes, to pull version `0.1.0` Which is a production ready build, and I'll be using `dev` branch for pre-releases, and also testing purposes, with PRs, so Main isn't cluttered with code, which doesn't work.

**Comment by Vyvy-vi** [comment]
😄  You can open another issue on this `support` repo for "Contributors needed: <project_name>" with details 🤓

**Comment by janaSunrise** [comment]
Oh Cool! I'll do that for sure :D

**Comment by Vyvy-vi** [comment]
welp, stalebot is getting itchy fingers

**Comment by janaSunrise** [comment]
Yeah 😂 😂 I have stopped working on HypixelIO for a while, got other projects, and no contributors either, Might make a PR to get some help :)

**Comment by eddiejaoude** [comment]
We will ignore stalebot for this 🤓 . I removed the label.

Maybe we should do a live stream today reviewing some open source projects? This issue will be 2nd 🎉

**Comment by Vyvy-vi** [comment]
> Yeah 😂 😂 I have stopped working on HypixelIO for a while, got other projects, and no contributors either, Might make a PR to get some help :)

I don't see any issues open on your repo...
Maybe you could open some, maybe we could contribute a little?

**Comment by eddiejaoude** [comment]
Reviewed in live stream https://youtu.be/_JjV9n-G-p0

Looks great, some of my thoughts:
- Use Issues to track work and make it easier for the community to get involved
- Project board is great, but suggest converting to issues for discoverability and so people can comment (join the conversation)
- Suggest adding a Code of Conduct https://github.com/janaSunrise/HypixelIO/community
