### ISSUE TITLE
Nightbot blocking links of GithubLabs also

### ISSUE THREAD

**Issue by SKULLXL** [EddieJaoudeCommunity/support#452]
In the Discord server Nightbot blocks all links of normal members other then GitHub and YouTube links. But i feel that GitHub Labs links also should be allowed. For instances someone today asked where he can learn bout GitHub i tried to give him the GitHub Labs link but Nightbot blocked it. I feel that GitHub Labs link can be allowed.

**Comment by nhcarrigan** [comment]
I can confirm that `https://lab.github.com/` is auto-modded by Nightbot.

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 - I will update nightbot now

**Comment by eddiejaoude** [comment]
I updated nightbot allowed list, let me know if anything else is needed

```
github.com
github.io
youtube.com
twitter.com
linkedin.com
facebook.com
~/[\s]*\.github\.io/i
dev.to
medium.com
gist.github.com
lab.github.com
stars.github.com
```
