### ISSUE TITLE
Review my open source project please

### ISSUE THREAD

**Issue by RasPiPkr** [EddieJaoudeCommunity/support#455]
Thank you
https://github.com/RasPiPkr/lottery

After you've reviewed my lottery project, if you want to look at my profile too.

**Comment by eddiejaoude** [comment]
Thank you @RasPiPkr for sharing your open source project 👍 - I will review it in one of my next videos / live streams 🤓

**Comment by eddiejaoude** [comment]
Reviewed in live stream https://youtu.be/_JjV9n-G-p0

Looks great 👍 , some of my thoughts:
- Deploy project for a demo
- Suggest create a tag/release
- QuickStart to README
