### ISSUE TITLE
Suggestion for README.md

### ISSUE THREAD

**Issue by GreyhoundProject** [EddieJaoudeCommunity/support#466]
Hello. This is my first issue, so I hope I have done this correctly, and apologies if not.

I was just reading the support readme, and there is a sentence which says: _... a friend or a colleague on Discord/MS Teams/Slack/YouTube/whatever, they may have found ..._.

Because the list contains only one space in MS Teams, the sentence breaks here. Maybe a comma separated list or different wording would give better formatting?

It might just be because I viewing the text on a mobile device but the text was harder to follow with the unexpected line break.

All the best,
James

**Comment by Vyvy-vi** [comment]
Can confirm, the line break is also there on laptops.
Perhaps we could consider comma separated? `,`

**Comment by eddiejaoude** [comment]
Thanks for raising @GreyhoundProject 👍 

Can I make a suggestion for next time, can you add a screenshot, it really helps give more context 🤓

**Comment by GreyhoundProject** [comment]
Absolutely, thanks for the feedback. Always looking to improve how I contribute!

Thanks,
James

**Comment by eddiejaoude** [comment]
Awesome, thank you @GreyhoundProject 👍
