### ISSUE TITLE
[Q]: Bug Template description change?

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieJaoudeCommunity/support#468]
### **Description**

A brief description of the question or issue:
The current `Bug` issue description is not apt and descriptive.
![Screenshot 2020-11-30 at 5 33 12 PM](https://user-images.githubusercontent.com/62864373/100608476-79d02e80-3332-11eb-9be2-8505ab3b8776.png)

Perhaps we can change it to something like- "Report a bug on this repo" 
(Also, perhaps we could replace that BUG template with something like: REPO-Issue:_report problems or suggestions for the repo_)

### Why is this essential?
The support repo is often like the entry gates to our community.
Often when some new member notice bugs/issues on the repo, it's like an opportunity to start contributing, but they might be confused due to the lacking issue description. 

### community info: 
You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)
Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by AllanRegush** [comment]
@Vyvy-vi Do you want to work on this?

**Comment by Vyvy-vi** [comment]
Yes, I can 👍

**Comment by eddiejaoude** [comment]
Thank you both, great team work 👍
