### ISSUE TITLE
[BUG]: The all-contributors badge isn't updated

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieJaoudeCommunity/support#469]
## **Description**

A brief description of the question or issue, also include what you tried and what didn't work:
The repository's `all-contributors` badge displays `2 contributors`, however, the repo has `16 contributors`
 This might be due to `all-contributors bot` not being used

## Why is this essential?
The `support` repo is like a cover-page of our organisation.
Many open source enthusiasts might find this small issue as something in bad taste since the presence of the `all-contributors` badge represents that we adopt [all-contributors](https://allcontributors.org/) specification but it shows 2 contributors when the repo has total 16.

## **Screenshots**
The all-contributors Badge on `support` repo:
![Screenshot 2020-11-30 at 5 43 51 PM](https://user-images.githubusercontent.com/62864373/100609266-b94b4a80-3333-11eb-9d3c-8629576a032d.png)

The Contributors Column:
![Screenshot 2020-11-30 at 5 45 58 PM](https://user-images.githubusercontent.com/62864373/100609390-edbf0680-3333-11eb-9a42-343471668018.png)

## Suggested actions:
We can do either of the following-
1- run @all-contributors bot, to add contributors
OR
2- Make an action to update repo on [push, pull_request], and update no. if there's a new contributor
OR
3- remove the badge from the repo
(There might be other methods. Thought?)

## Community Info:
You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)
Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by AllanRegush** [comment]
I think @eddiejaoude had decided not to use `all-contributors`

**Comment by Vyvy-vi** [comment]
So, should we remove the badge from the readme?

**Comment by eddiejaoude** [comment]
Thank you for noticing and raising. Yep GitHub shows contributors now, so I don't think `all-contributors` is needed anymore
