### ISSUE TITLE
Please add me to the Organisation

### ISSUE THREAD

**Issue by meenal21** [EddieJaoudeCommunity/support#47]
Hey @eddiejaoude ! i have just started using Github, could you add me to the organisation.

**Comment by eddiejaoude** [comment]
Sure 👍 . Invitation sent 🤓 

Don't forget to make it public otherwise only you will be able to see it. You can do this by finding your name and selecting `public` next to your name here https://github.com/orgs/EddieJaoudeCommunity/people
