### ISSUE TITLE
Would appreciate being a part

### ISSUE THREAD

**Issue by dumbcoder7** [EddieJaoudeCommunity/support#471]
Please invite me to the GitHub Community Organisation. 

I got interested in Open Source only recently, after watching Eddie's amazing video on FreeCodeCamp.
I am fairly new to the community, and am not entirely sure about what is the best way to contribute, and how? I have been contributing to individual projects of users, but have not been able to solve complex issues that all developers seem to be solving easily. I want to be part of this community, to really understand what Open Source is all about, and keep learning.

Name: Aditya Raute
Username: dumbcoder7

Additional Context:

*Where did you meet Eddie?*
YouTube Video on FreeCodeCamp's channel

*What do you like about this community/ why do you want to join*
I honestly do not know much about how this community is supposed to work. I am joining to learn, explore and contribute to Open Source projects in my capacity (which ain't much but still).

Hope the application comes through :nerd_face:

**Comment by dumbcoder7** [comment]
Okay, I might look like a complete noob here, but I am not able to add a label to my issue, neither has the bot added it. Even though I selected the template.

Is it perhaps because I am not a contributor?

**Comment by nhcarrigan** [comment]
I believe you need to have write access on the repository to edit the labels.

**Comment by eddiejaoude** [comment]
I think the template has the label, it usually gets added correctly 🤔  https://github.com/EddieJaoudeCommunity/support/blob/main/.github/ISSUE_TEMPLATE/invitation.md

Thanks @nhcarrigan , I think it is a glitch in the matrix, lets keep an eye on it 🤓

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
