### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Frakko** [EddieJaoudeCommunity/support#480]
Please invite me to the GitHub Community Organisation. 

Name: Francesco

Discord Username(if exists): Frakko#0001

Additional Context:
Where did you meet Eddie? I found out about Eddie through his YouTube channel.

What do you like about this community/ why do you want to join? I'm new to the Open Source world and after watching some YouTube videos from Eddie, I found out about this community. I'd love to start my path from here and improve, not only as a developer, but also as a person! 😄

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
