### ISSUE TITLE
[Marketing] How to raise the profile of this?

### ISSUE THREAD

**Issue by stemount** [EddieJaoudeCommunity/support#5]
So many good things come out of this project e.g. we could have ANYBODY livestream to their audience go through the issue queue and the community in the Twitch/YT chat could essentially "pair with everybody" on it!

The idea is to raise the profile of everybody who helps on the issues and livestreamers like @eddiejaoude @praveenscience @HarshKapadia2 can go through the queue with their audience!

**Comment by stemount** [comment]
This can be revisited when it is appropriate.

**Comment by eddiejaoude** [comment]
I think this is a good idea, but would be good to get our docs in order first, so when new people arrive it is clear. We are still setting the foundations at the moment. I dont expect it to be finish before we do a bigger marketing push, but at least more of the basics, of what projects we have, how people can get involved etc
