### ISSUE TITLE
Issue template label not assigned

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/support#505]
**Description**

A brief description of the question or issue, also include what you tried and what didn't work:

**Stack**

Project stack or language (eg. Frontend):

**Working Environment**

Operating System (eg Linux):

Browser (eg. Chrome):

Device (eg. Laptop or Phone):

**Screenshots**

Please add a screenshot if applicable

[Optional] **Additional Context**

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by dumbcoder7** [comment]
Umm, I got assigned this issue but I am confused. What exactly happened? Do I have to do something?

**Comment by eddiejaoude** [comment]
I assigned it to you because you already fixed it in PR #495 - so nothing for you to do, you already did the work 🤓
