### ISSUE TITLE
Dummy_Bank

### ISSUE THREAD

**Issue by aniketsingh98571** [EddieJaoudeCommunity/support#515]
Items we can review on a live stream:

- aniketsingh98571
- [Dummy_Bank](https://github.com/aniketsingh98571/Dummy_Bank)
- [Portfolio](https://aniketsingh98571.github.io/Web-Portfolio/)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by AllanRegush** [comment]
`Dummy_Bank` is archived - I can't raise an issue to help make the project better. Is still in development?

**Comment by aniketsingh98571** [comment]
@AllanRegush  I have just raised an issue for reviewing my documentation.

**Comment by AllanRegush** [comment]
I can't see it, where did you raise the issue? I can't add to the project because it's read only(`archived`).

**Comment by AllanRegush** [comment]
@aniketsingh98571 Any reason to be closing this issue? I was just pointing out that I can't contribute if the project is read only. 😞

**Comment by BOLT04** [comment]
> I can't see it, where did you raise the issue?

@AllanRegush I think @aniketsingh98571 raised this issue for Eddie to review the documentation of that repository, so probably the `README` since I didn't see any `docs` folder or a wiki.

**Comment by AllanRegush** [comment]
@BOLT04 Ah, makes sense - I thought this was a review about how to make your repository more inclusive for contributors.

**Comment by AllanRegush** [comment]
Also, anyone can review the docs. But they can't raise and issue if they find something.

**Comment by eddiejaoude** [comment]
@aniketsingh98571 I did not get to reviewing this yet, do you want to leave it open so I can review it in a video / live stream?
