### ISSUE TITLE
Committing to a forked Repo doesn't create a Green Square on Github

### ISSUE THREAD

**Issue by yalematta** [EddieJaoudeCommunity/support#52]
I've got one beginner Github Question!
If I fork a Repo and I add code, commit and push to my own forked Repo: no green squares are being shown! 
Should I create a Pull-Request with my changes for the green square to show up?

**Comment by eddiejaoude** [comment]
Great question @yalematta  👍 

If the `commit` is not in the *default* branch in any repo (fork or your own), then it does not show the green square until it is *merged* into the *default* branch (if a fork, it is best not to make any changes in the *default* branch as this should be kept up to date with `upstream`).

Raising an **Issue** or **Pull Request** will give you another green square in addition to any commits that end up in the *default* branch.

After a **Pull Request** is merged and commits are in the default branch, that is at least 3 open source activities (including the creating of the **Issue** - the darkness of the green square will depend on the rest of the activity on the graph.

**Comment by yalematta** [comment]
Very clear! Thank you for your quick answer 👍
