### ISSUE TITLE
Suggestion: update a FAQ instruction in README.md 

### ISSUE THREAD

**Issue by jasontwuk** [EddieJaoudeCommunity/support#522]
In the README.md >> FAQ >> How do I set the Organization to Public >>  ii. Click on people in this box, the original image is:
![93422448-09f0f280-f871-11ea-94d8-c48924a0222e-1](https://user-images.githubusercontent.com/13745974/101379386-1bfc9300-38ac-11eb-8f9e-b5ec5f1ef9e0.png)

When I first tried to follow the instruction (Click on people in this box), I clicked on people’s images instead of the text above them, which led me to the wrong place. 
I think it needs a red circle (see the image below) to indicate where readers should click, it will add more clarity.
![93422448-09f0f280-f871-11ea-94d8-c48924a0222e](https://user-images.githubusercontent.com/13745974/101379459-3171bd00-38ac-11eb-9037-68b97ff34cdf.png)

**Comment by AllanRegush** [comment]
Great Suggestion 👍 Would you like to work on this?

**Comment by jasontwuk** [comment]
Yes, I will. 🙂

**Comment by eddiejaoude** [comment]
Thank you both 👍
