### ISSUE TITLE
Typo in Repository topics

### ISSUE THREAD

**Issue by tintindas** [EddieJaoudeCommunity/support#524]
**Description**

In the topics it should probably be documentation instead of documemtation.

**Screenshots**

![image](https://user-images.githubusercontent.com/47525983/101445900-4ef46480-3948-11eb-806e-cf5a4e49edb2.png)

**Comment by eddiejaoude** [comment]
Thank you 👍 

Fixed...

<img width="569" alt="Screenshot 2020-12-08 at 10 09 11" src="https://user-images.githubusercontent.com/624760/101470109-7bef4a00-393d-11eb-930e-325b02bc23a7.png">
