### ISSUE TITLE
Add Eddie emoji

### ISSUE THREAD

**Issue by jveer634** [EddieJaoudeCommunity/support#530]
@eddiejaoude 
Can you add this image to the community..??
Please..

![eddietest](https://user-images.githubusercontent.com/47923507/101515480-66613b00-39a4-11eb-904e-dd9d2db7ac8f.png)

**Comment by Vyvy-vi** [comment]
this has been added on the server 👍  🥳

**Comment by eddiejaoude** [comment]
awesome! we can close this issue now 👍
