### ISSUE TITLE
Suggestion: update a FAQ instruction in README.md

### ISSUE THREAD

**Issue by jasontwuk** [EddieJaoudeCommunity/support#540]
This is a follow up issue from #527.

The issue is in README.md >> FAQ >> How do I set the Organization to Public >> iii. Search for yourself in this input.

In order to have a more coherent style, we could change step iii to something like this (see below).

iii. Search for your name or username in the blue circled input:
![screenshot](https://user-images.githubusercontent.com/13745974/101762892-e9ce7980-3ad5-11eb-8824-59ab4623bf81.png)

**Comment by AkshayaKulasekaran** [comment]
Seconded 👍
