### ISSUE TITLE
I will love to join this community

### ISSUE THREAD

**Issue by iamkennis** [EddieJaoudeCommunity/support#550]
**Description**

A brief description of the question or issue:

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by Vyvy-vi** [comment]
@eddiejaoude This is an invite request
(Sorry for the ping, the label is different, might have been difficult to navigate for you through all the notifications)

**Comment by eddiejaoude** [comment]
Thank you for the ping @Vyvy-vi 👍 - I have over 600 GitHub notifications in the last 48 hours 😱 , but I will send invitations now 🤓

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by Vyvy-vi** [comment]
🙂
