### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ThatNiftyNerd** [EddieJaoudeCommunity/support#553]
Please invite me to the GitHub Community Organisation. 

- #### Name: ThatNiftyN3rd

- #### Discord Username(if exists): 

- #### Additional Context: So I stumbled on Eddie's content on youtube a few weeks ago, and then again on his most recent youtube video on Brad Traversy's channel. Currently teaching myself to code using free resources online, so I figured I might as well find an open source community to help brush up my skills, which is what I hope to achieve here.

 

:nerd_face:

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
