### ISSUE TITLE
How to add GitHub Stats to GitHub Profile or README.md file

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#56]
**Description**

A brief description of the question or issue:

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Comminity [here](https://github.com/EddieJaoudeCommunity)
GitHub Stats are automatically update as we're get more involve in PR, making issues, REPOs etc.
Or do we have to manually update GitHub stats

**Comment by eddiejaoude** [comment]
You need to use @anuraghazra service to do it, it can be achieve with:

Change the ?username= value to your GitHub's username
```
[![Anurag's github stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)
```

Full docs https://github.com/anuraghazra/github-readme-stats

**Tip: you can go to anyones custom profile and view the `README.md` file, then click `raw` to see how they achieve it**

**Comment by mohit01-beep** [comment]
yeah i found good resource on site you give above but there's something wrong happening here
I write most language code in readme file at bottom but it cover area above on other lines
can you check why it's happening 
https://github.com/mohit01-beep
here's my profile link

**Comment by eddiejaoude** [comment]
I think it is because you don't have a line break after your list, so markdown thinks the image is part of the list and not a separate block

---

### Hi there 👋

- 🔭 I’m currently working on ...some small web projects using HTML, CSS and JS
- 🌱 I’m currently learning ...JAVA, HTML, CSS and JS
- 👯 I’m looking to collaborate on ...Open Source Projects and Hackathons
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...anything i will try to help you if i can 
- 📫 How to reach me: ... 
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=mohit01-beep&layout=compact)](https://github.com/mohit01-beep/github-readme-stats)

**Comment by mohit01-beep** [comment]
oh i found what was wrong, also i want to ask where can i get these emoji's codes and icons

**Comment by eddiejaoude** [comment]
> oh i found what was wrong

what was wrong @mohit01-beep ? remember think of sharing with the community

**Comment by mohit01-beep** [comment]
> > oh i found what was wrong
> 
> what was wrong @mohit01-beep ? remember think of sharing with the community

it's just you have to put - on starting of each line for line break,
 i didn't knew that was line break i just tried and yeah i'm right - is line break in README.md file

**Comment by mohit01-beep** [comment]
> oh i found what was wrong, 
 **also i want to ask where can i get these emoji's codes and icons**
please check this 2nd line of emoji and icons in README @eddiejaoude

**Comment by eddiejaoude** [comment]
> it's just you have to put - on starting of each line for line break,
i didn't knew that was line break i just tried and yeah i'm right - is line break in README.md file

Ok so I what I suggested worked https://github.com/EddieJaoudeCommunity/support/issues/56#issuecomment-672955265

**Comment by mohit01-beep** [comment]
how to add Icons/Logo in Readme file

**Comment by eddiejaoude** [comment]
I think that is a different question. If it is buried in another question it won't help the rest of the community. Please raise a new question and include an example of what you are looking for

**Comment by alqusi1992** [comment]
[![Anurag's github stats](https://github-readme-stats.vercel.app/api?username=alqusi1992)](https://github.com/alqusi1992/github-readme-stats)

All you need to change the username value.
