### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ahammadshawki8** [EddieJaoudeCommunity/support#561]
Please invite me to the GitHub Community Organisation. 

- #### Name: Ahammad Shawki
-  You can find other details about me in my GitHub profile.

### Additional Context
- Where did you meet Eddie?    Ans: Youtube channel
- What do you like about this community/ why do you want to join?   Ans: I want to be an ideal open-source citizen.

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by ahammadshawki8** [comment]
I haven't got the invitation yet. Where can I find it?

**Comment by ahammadshawki8** [comment]
sorry for the previous mail. I just found the invitation. Thank you very
much.
