### ISSUE TITLE
Awsome Badges

### ISSUE THREAD

**Issue by MallikarjunHt** [EddieJaoudeCommunity/support#569]
Awsome badges for `Licence`, `Discord`, `Open-Source`, `Creative Commons Licenses` and more
refer this for more info   [Badges](https://github.com/Naereen/badges)
___
![github](https://img.shields.io/github/followers/MallikarjunHt?label=Followers&logo=GitHub&style=for-the-badge)

**Comment by Vyvy-vi** [comment]
Those do look nice 😄

**Comment by BOLT04** [comment]
This is really cool @MallikarjunHt, thanks for sharing 👍. I support adding some to our repos 😃

**Comment by jasontwuk** [comment]
I always wonder where people get those badges when I see them, now I know. Thank you. 🙂

**Comment by Vyvy-vi** [comment]
slightly relevant to this-
http://forthebadge.com/
shields.io

provide customisable badge APIs

**Comment by eddiejaoude** [comment]
I have used https://shields.io and it is great 👍

**Comment by MallikarjunHt** [comment]
Thanks a lot. :smile:
