### ISSUE TITLE
How can i become  Arctic Code Vault Contributor

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#57]
**Description**

A brief description of the question or issue:

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Comminity [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
From their documentation, I think it is too late...
> GitHub will capture a snapshot of every active public repository on 02/02/2020 and preserve that data in the Arctic Code Vault.

https://archiveprogram.github.com

> ## ARCTIC WORLD ARCHIVE
> On February 2, 2020, GitHub captured a snapshot of every active public repository, to be preserved in the GitHub Arctic Code Vault. This data will be stored on 3,500-foot film reels, provided and encoded by Piql, a Norwegian company that specializes in very-long-term data storage. The film technology relies on silver halides on polyester. This medium has a lifespan of 500 years as measured by the ISO; simulated aging tests indicate Piql’s film will last twice as long.

**Comment by mohit01-beep** [comment]
So, it will not happen again or i'm asking it has no use later to be a member of Arctic Code Vault

**Comment by eddiejaoude** [comment]
At the moment I think it is not possible to become a ACV member until they do it again

**Comment by mohit01-beep** [comment]
oh, ok it's good atleast i have their badge on my profile
