### ISSUE TITLE
[discord-server]: Add "tenor" and "giphy" to allowed links

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieJaoudeCommunity/support#580]
## **Description**

A brief description of the question or issue:

Tenor GIF links get deleted by Nightbot

GIFs are an integral part of discord, and are used quite a lot in chats by almost all discord users.
It might be non-inclusive if only regulars could post gif-links from Tenor, and not all users.

### Suggested/Requested action:
Add giphy and tenor to the ignore-list of Nightbot

### Context:
![Screenshot 2020-12-22 at 10 50 00 PM](https://user-images.githubusercontent.com/62864373/102915582-0c826a00-44a8-11eb-9f78-88b9ae0aba3a.png)

---
You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)
Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks for the issue. I have updated NightBot to allow Giphy and Tenor. Here is the complete list at the moment...

```
github.com
github.io
youtube.com
twitter.com
linkedin.com
facebook.com
~/[\s]*\.github\.io/i
dev.to
medium.com
gist.github.com
lab.github.com
stars.github.com
tenor.com
giphy.com
```

**Comment by eddiejaoude** [comment]
We probably need someone to test it out though 🤔

**Comment by Vyvy-vi** [comment]
It works :)
![Screenshot 2020-12-28 at 3 57 36 PM](https://user-images.githubusercontent.com/62864373/103207882-6f02bc80-4925-11eb-9ae4-9e7910a86e07.png)

**Comment by eddiejaoude** [comment]
Awesome! Thank you for testing @Vyvy-vi 👍
