### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by mauricelacerda** [EddieJaoudeCommunity/support#581]
Please invite me to the GitHub Community Organisation. 

- #### Name: Mauricio

- #### Discord Username(if exists): dev.mauricio

- #### Additional Context:

I've been following Eddie's YouTube channel for a few months now and I love the content he puts up and the value he provides for the open source community.

 
I've always been a big believer in the open source movement and I want to start contribuing to it for a while. I didn't do so before because I didn't feel ready for it. Eddie's videos inspired me to start taking action to change this.

:nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
