### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [EddieJaoudeCommunity/support#596]
Please invite me to the GitHub Community Organisation. 

- #### Name: Nitesh Thapliyal

- #### Discord Username(if exists): 
 Nitesh Thapliyal#3765

- #### Additional Context:
 
I meet Eddie on youtube

 
This community help newbie like me to know more about open source that's what I like about it and I want to join this community because I want to contribute more as I am new I have done only 10 contributions so far, but I have learned a lot from that and now I want to learn more.
:nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
