### ISSUE TITLE
About changing username of Github profile

### ISSUE THREAD

**Issue by Shubham714** [EddieJaoudeCommunity/support#60]
**Description**

My question is, what are the consequences of changing the username of the GitHub profile?
do my contributions stays with my new username?

**Comment by jatin2003** [comment]
Yeah! Your contributions are not going anywhere when you change your username 😉

But It can have some other [side effects](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-github-username) 😁

**Comment by stemount** [comment]
as @jatin2003 mentioned **this has consequences** and has linked to a helpful article on this, so closing this issue!

**Comment by eddiejaoude** [comment]
Thanks @stemount . I will add a `solved` label to the issue
