### ISSUE TITLE
huntr.dev - The place to protect open source

### ISSUE THREAD

**Issue by Jmimoni** [EddieJaoudeCommunity/support#61]
Just a quick little pitch... we are building the first open-source bug bounty platform. 

Traditional bug bounty programs are mostly sponsored by organizations, and hackers end up having to fight through multiple layers to get responses. They also focus on company code over open-source code.

Nowadays around 70% of used code is open source, and as we all know, vulnerabilities are constantly being identified in packages across the open-source ecosystem. 

Putting this all together, we came up with huntr.dev... We are now working to help maintainers monitor their packages for security issues, and when problems are found, we rally the community to create a fix!

I would love to hear your opinion on the idea, brand, website, and anything else you think might be useful! 

[huntr.dev](https://huntr.dev)

**Comment by stemount** [comment]
@Jmimoni I have come across your site before (somehow, SPOOKY! 🧙🏻), one UI tweak that would make me come back would be a count of PRs/entries/bounties/whatever you want to call against an issue. :)

raised here 💯 https://github.com/418sec/huntr/issues/273

**Comment by Jmimoni** [comment]
@stemount great idea, thanks for opening an issue, It has been added to the backlog!

**Comment by stemount** [comment]
@Jmimoni @eddiejaoude Gonna close this issue as I think most will have had a look over and added any comments to the issue queue.
