### ISSUE TITLE
Joining support group

### ISSUE THREAD

**Issue by virenkhandal** [EddieJaoudeCommunity/support#62]
**Description**

A brief description of the question or issue:

Hey Eddie! Just saw your latest video on Github Sponsors and absolutely loved it... would you mind adding me to the Eddie Jaoude community on Github

**Comment by eddiejaoude** [comment]
Invitation sent. Dont forget to make it public if you want it to appear on your profile for other people to see - you will find it to the right of your name https://github.com/orgs/EddieJaoudeCommunity/people
