### ISSUE TITLE
How to check if a users browser in dark mode/day mode?

### ISSUE THREAD

**Issue by stemount** [EddieJaoudeCommunity/support#63]
**Description**

Stolen from Slack

![image](https://user-images.githubusercontent.com/150512/90278606-8aca6200-de5f-11ea-9ad4-c46d96f37353.png)

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by stemount** [comment]
stolen from @NathanDennis

**Comment by NathanDennis** [comment]
That's not me you silly goose!

But, I'd recommend these resources:

CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

FreeCodeCamp's take on why CSS by itself might not be enough: https://www.freecodecamp.org/news/how-to-detect-a-users-preferred-color-scheme-in-javascript-ec8ee514f1ef/

**Comment by stemount** [comment]
Excellent thanks @NathanDennis I am not even sure WHO is the right github username to tag! Let's hope it gets back to @nateknown.... somehow!!

**Comment by stemount** [comment]
Not sure why I didn't close this issue as @NathanDennis nailed it
