### ISSUE TITLE
Members in Discord don't have permissions to tag Moderators

### ISSUE THREAD

**Issue by HannWeb** [EddieJaoudeCommunity/support#635]
**Description**

![image](https://user-images.githubusercontent.com/69229784/103604836-d39aba00-4ed7-11eb-93ac-fb8c7936bffa.png)

**Comment by eddiejaoude** [comment]
Oh this is so important, thank you 👍

**Comment by eddiejaoude** [comment]
Fixed...

<img width="1007" alt="Screenshot 2021-01-06 at 10 27 39" src="https://user-images.githubusercontent.com/624760/103758251-d990b800-5009-11eb-99ba-d846b2a5775e.png">
<img width="534" alt="Screenshot 2021-01-06 at 10 27 29" src="https://user-images.githubusercontent.com/624760/103758261-db5a7b80-5009-11eb-9c4a-19402caeace6.png">
