### ISSUE TITLE
Link to Eddie's Personal Website http://eddiejaoude.github.io/

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [EddieJaoudeCommunity/support#636]
**Description**
The link to eddie's personal website is redirecting using wrong URL. There is an additional space at the end of the URL which makes it break.
I have noticed this in the last two videos:

[What are MLH, GSOC, Outreachy? Open Source discussion with Kunal Kushwaha #Github #DevRel](https://www.youtube.com/watch?v=BQXJMEkAtAQ)

[Starting 2021 with an AMA and let's get you into Open Source #Github #OpenSource #DevRel](https://www.youtube.com/watch?v=CNTnHivCI7A)

**Stack**

Project stack or language (eg. Frontend):
Frontend -> YouTube Description Box

**Working Environment**

Operating System (eg Linux):
MacOS 10.15.7
Browser (eg. Chrome):
Chrome
Device (eg. Laptop or Phone):
Macbook Pro
**Screenshots**
The first link:
<img width="536" alt="Screen Shot 2021-01-05 at 09 12 19" src="https://user-images.githubusercontent.com/61970868/103608960-1ee3b580-4f36-11eb-80b4-ea4bbf3e9ca0.png">
Result:
<img width="917" alt="Screen Shot 2021-01-05 at 09 12 38" src="https://user-images.githubusercontent.com/61970868/103608974-2a36e100-4f36-11eb-9357-2af571ed70c6.png">

**Comment by eddiejaoude** [comment]
Oh no 😱 , this is bad of me!! Thank you for raising the issue! 👍

**Comment by eddiejaoude** [comment]
I went back throngh the last few month of videos and fixed them. Thank you again for highlighting this bug ❤️ , I can not believe it has been broken for so long 😱 😢 

I updated to use my custom url http://eddiejaoude.co.uk 🤓
