### ISSUE TITLE
Please invite me to the GitHub Community Organization. Thanks :)

### ISSUE THREAD

**Issue by Utkarsh299-tech** [EddieJaoudeCommunity/support#647]
Please invite me to the GitHub Community Organisation. 

- #### Name: Utkarsh Singh

- #### Discord Username(if exists): Utkarsh Singh#9994
 

- #### Additional Context:
 

       YouTube

 
  
      To improve my communication, collaboration, and of course technical skills. Also, to grow my profile and network to standout.

:nerd_face:

**Comment by eddiejaoude** [comment]
You are already in the organisation. The issue was raised 3 days ago https://github.com/EddieJaoudeCommunity/support/issues/612

**Comment by Utkarsh299-tech** [comment]
> You are already in the organisation. The issue was raised 3 days ago #612

Oh, I had a bit of confusion. Thank you for clarifying, @eddiejaoude!

**Comment by eddiejaoude** [comment]
no problem 🤓 , we all learn by trying 👍 - its GitHub, it is always about doing and trying 💪
