### ISSUE TITLE
Organization Invitation

### ISSUE THREAD

**Issue by Abhay2611** [EddieJaoudeCommunity/support#66]
**Description**

Hi there, I'm Abhay looking forward to join your awesome open source community. Add me up, I would like to  learn and know more about open source contributions and a lot of other stuff!

**Comment by eddiejaoude** [comment]
Invitation sent @Abhay2611 , welcome to our open source community 🤓 . Dont forget to make it public if you want it to appear on your profile, but selecting public next to your name here after you have accepted https://github.com/orgs/EddieJaoudeCommunity/people
