### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ritik307** [EddieJaoudeCommunity/support#666]
Please invite me to the GitHub Community Organisation. 

- #### Name: Ritik

- #### Discord Username(if exists): PinkDog307#7439

- #### Additional Context: Youtube

 

:nerd_face: I am new to open source community and I am eager to learn and contribute to the community

**Comment by viraldevpb** [comment]
Please invite me to the GitHub Community Organisation.

* **Name: Prathamesh**
* **Discord Username: Pratham#3453**
* **Additional Context: Youtube**

🤓 I am new to the open source community and I am eager to learn and contribute to the community

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by viraldevpb** [comment]
I am Not Finding My Name There.
How can I find it My Name there?

**Comment by eddiejaoude** [comment]
I see your name there. Can you take a screenshot?

**Comment by viraldevpb** [comment]
Okay Sure.
But I have Joined Your Organizations what I Have to do Next.!

**Comment by Vyvy-vi** [comment]
@viraldevpb Welcome to EddieJaoudeCommunity-!
You could head over to https://github.com/EddieJaoudeCommunity/hacktoberfest-practice , if you need practice on opensource git/github workflow environment.

You could checkout: https://github.com/EddieJaoudeCommunity/support/discussions/categories/first-timers and  https://github.com/EddieJaoudeCommunity/support/issues?q=is%3Aopen+is%3Aissue+label%3A%22open+source+review%22 for first-timer issues, and issues on projects that need help-!

You could checkout our other repos and look if there's something you would like to help with.

OpenSource FTW-! 🟩
