### ISSUE TITLE
As a project maintainer how to test an incoming PR before merging

### ISSUE THREAD

**Issue by gagangaur** [EddieJaoudeCommunity/support#67]
**Description**

Someone filed a pr into mine project and I was reviewing it to make sure that it won't break any functionality or is it really working or not that's the case here

**Stack**
React.js (frontend)

**Comment by eddiejaoude** [comment]
This is a great question @gagangaur 👍 

I see a couple of ways:

1. create a test branch in your repo, update the PR to merge it into a temporary branch
2. clone the forked repo and checkout their branch

I would be interested to know what others do?

**Comment by eddiejaoude** [comment]
I found a 3rd way which is the better...

3. Download a patch from the PR that you can apply locally to test, by appending `.patch` to the PR url. For example https://patch-diff.githubusercontent.com/raw/EddieJaoudeCommunity/EddieBot/pull/176.patch

**Comment by gagangaur** [comment]
great @eddiejaoude  💯 but if we talk about production environment then which approach is recommended 🤔

**Comment by eddiejaoude** [comment]
I think `option 3` is always the best option, it can be applied locally or to a branch to be deployed to to a `test` environment.

I do not see how `production` would fit in here, as only code that is reviewed, accepted and merged would ever make it to `production`

**Comment by gagangaur** [comment]
alright thanks @eddiejaoude here by production I mean that the master branch in which all pr's are getting merge. so I am closing this up here.

**Comment by eddiejaoude** [comment]
Ah ok. So I would have the `default` branch locally and apply the PR patch to test it locally - this will work for any branch, `main`, `master`, `develop` etc
