### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by JorgePiaggio** [EddieJaoudeCommunity/support#670]
Please invite me to the GitHub Community Organisation. 

- #### Name: Jorge

- #### Discord Username: JorgeP#7639

- #### Additional Context: I'm already on Eddie Discord Channel and Eddiehub Team for MLH. Met Eddie watching the video about how to contribute to open source.

 
I'm here to learn from the community on how to contribute to open source
:nerd_face::nerd_face::nerd_face::nerd_face::nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps

**Comment by JorgePiaggio** [comment]
thanks for accepting @mikeysan!
