### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by abhishek7389** [EddieJaoudeCommunity/support#673]
Please invite me to the GitHub Community Organisation. 

- #### Name: Abhishek Sharma

- #### Discord Username(if exists): abhisheksharma7389#8501

- #### Additional Context: I meet Eddie in tomorrow's MLH local hack day meet up for EddieHub, and I'm very inspired by the community, there are peoples who encourage you and the best thing is the spirit of sharing and learning. 

 
Like I just said the spirit of learning & sharing is the best thing I experienced tomorrow.
:nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
