### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by abhijeetk698** [EddieJaoudeCommunity/support#684]
Please invite me to the GitHub Community Organisation. 

- #### Name: Abhijeet Jha

- #### Discord Username(if exists): abhijeet#3997

- #### Additional Context:
> Where did you meet Eddie?: 

Watched his video on Complete guide to open source at freecodecamp.org youtube channel and found his channel on youtube through this. 

>What do you like about this community/ why do you want to join 

what I like about this community is that the community has a mix of people from every level of expertise from noob to pro and it feels quite welcoming to me, I want to grow my interest in opensource and up my skills and knowledge and grow together.

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
