### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by vat0599** [EddieJaoudeCommunity/support#685]
Please invite me to the GitHub Community Organisation. 

- #### Name: Srivatsav Raghu

- #### Discord Username(if exists): Srivatsav Raghu#3970

- #### Additional Context:
  - Where did you meet Eddie?
Honestly, in a youtube recommendation a year back. But now I'm following his work and recently saw this [youtube video](https://www.youtube.com/watch?v=braWUyC77z4) and wanted to become a member of this organization.

  - What do you like about this community/ why do you want to join?
More than Eddie's work, the fact that Eddie is so motivated (I mean I could literally see how happy he is when hears opensource!) keeps people like us also fall in love with opensource, and boosts us towards contributing to the community. So I feel this is a right place to be and I could learn a lot through the way.

:nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
