### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Mayank0255** [EddieJaoudeCommunity/support#687]
Please invite me to the GitHub Community Organisation. 
- #### Name: Mayank Aggarwal

- #### Discord Username(if exists): Mayank#9665

- #### Additional Context:
>Where did you meet Eddie?

In a live stream he did recently with Kunal Kushwaha.

>What do you like about this community/ why do you want to join

I usually don't watch that much live streams, but this one was really good and I was able to see that Eddie wants to help the community desperately and the way he was explaining things was really great and that is the reason I feel there is no other better place to learn to contribute to OSC.

:nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
