### ISSUE TITLE
merge vs squash and merge vs rebase and merge

### ISSUE THREAD

**Issue by gagangaur** [EddieJaoudeCommunity/support#69]
![{6AF71647-B9C3-4FAF-B88F-3FF5140BA538} png](https://user-images.githubusercontent.com/40167245/90338425-3661e680-e007-11ea-94c7-6eba062d7269.jpg)

> ## In-depth difference between these three.
> ## When to use which
> ## Which one is recommended to use when working on a big project in collaboration

### *you can do a video by the way if you want and put above image as a thumbnail (as clickbait)* 😜

**Comment by eddiejaoude** [comment]
I will probably do a video on this in the future, but I will answer it now as I have a bit of a video queue at the moment 😂 

- `create a merge commit` will add a new commit with the merge, so in the history you will see when it was merged and all the other commits are in the history too
- `squash and merge` will still create a new commit but all the commits in the branch will be squashed into a single commit, so the history remains super clean, then it is possible to cherry pick out features
- `rebase and merge` will rewrite history so the commits in the PR are on top regardless of when the original commit was

More information in the GitHub docs https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges
