### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by agriyakhetarpal** [EddieJaoudeCommunity/support#692]
Please invite me to the GitHub Community Organisation. 

- #### Name: Agriya Khetarpal

- #### Discord Username(if exists): RocketRaja#0906

- #### Additional Context: None
#### Where did you meet Eddie?
A friend talked about him and asked me to join
#### What do you like about this community/ why do you want to join?
I want to learn more about open-source and improve my GitHub profile

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
