### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by ankurg132** [EddieJaoudeCommunity/support#700]
Please invite me to the GitHub Community Organisation. 

- #### Name: Ankur Gupta

- #### Discord Username(if exists):  AG#5783

- #### Additional Context: 
> Where did you meet Eddie:

I met him through the Major League Hacking Local Hack Day event, I've seen some of his videos too earlier, in the event I got to know about this whole community and I would love to be a part of such amazing community.

> What do you like about this community/ why do you want to join:

I would like to join here so that I can meet new people, find amazing ideas, to learn and grow together with contributing as much as I can.

:nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
