### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by saumya66** [EddieJaoudeCommunity/support#702]
Please invite me to the GitHub Community Organisation. 

- #### Name: Saumya Ranjan Nayak

- #### Discord Username(if exists): saumya264

- #### Additional Context: 

I met Eddie on the EquiCode & EddieHub guild meetup and talked around on Twitter and LinkedIn comments . 

 
I want to contribute more to opensource and also get help from some Machine and Deep Learning Enthusiasts like me and obviously ask Eddie some of the doubts that I may have .
:nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
