### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by galahad42** [EddieJaoudeCommunity/support#703]
Please invite me to the GitHub Community Organization. 

- #### Name: Amrit Anand

- #### Discord Username(if exists): Galahad#9318

- #### Additional Context:
#### Where did you meet Eddie?
I first saw Eddie on my LinkedIn feed and was totally fascinated by his achievements and work in Open-Source Community(side note: I'm still waiting for that connection invite acceptation Eddie). From there I went to his YouTube channel and finally his awesome discord community. It was because of him that I participated in my first hackathon under his guild(#Eddiehub FTW)
#### What do you like about this community/ why do you want to join?
After being in their discord community I saw all the people over there were really helpful and kind to everyone. I got my doubts cleared in just a few minutes plus they suggested better ways too. The thing I liked most about this community was that they are really inclusive and inviting community.
Also I'm stepping into open-source and I would love to start my journey in this amazing path with this amazing community 

:nerd_face:

**Comment by mikeysan** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
