### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by deepsingh132** [EddieJaoudeCommunity/support#704]
Please invite me to the GitHub Community Organisation. 

- #### Name: Mandeep Singh

- #### Discord Username(if exists):   deep132#5022

- #### Additional Context:
 I met or rather saw Eddie on code for cause's live stream and I was awestruck to hear about the contributions Eddie did and is currently doing to advance open source and the community. 

  I love how everyone is ready to just help each other no matter how much of help can they be and the fact that Eddie's Community is all about the saying that community first and open-source second. Now it's my favourite quote!

:nerd_face:

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
