### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Alenjojo** [EddieJaoudeCommunity/support#705]
Please invite me to the GitHub Community Organisation. 

- #### Name:  Alen Jojo

- #### Discord Username(if exists):  Alen Jojo#6363

- #### Additional Context:
Where did you meet Eddie?<br>
I came across Eddie through YouTube, then i started seeing him in other blogs describing about open sourcing thats i got interest in it.

What do you like about this community/ why do you want to join
<p>
I wish to pursue this is to evaluate my inherent abilities and potential. Although I have accumulated a strong foundational knowledge in this domain. I wish to learn , up-skill and acquire skills that can shape me as a valued professional in this field. I am ready to  use all my knowledge to achieve anything.</p>

:nerd_face:

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
