### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by kcoder63** [EddieJaoudeCommunity/support#710]
Please invite me to the GitHub Community Organisation. 

- #### Name: Karuna Tata

- #### Discord Username(if exists): Karuna#8722

- #### Additional Context: I met Eddie at local hack day and I'm glad to be part of Eddie hub

 

I am a great fan of Eddie , also am an active member of Eddiehub ,we have also talked in Linkedln comments , personally and even on Discord. I am aspiring to be a data scientist and I'm in first year of my college now and I know Eddie's guidance and his great stuff would definitely help me in achieving that goal.

:nerd_face:

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
