### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by adityathakurxd** [EddieJaoudeCommunity/support#711]
Please invite me to the GitHub Community Organisation. 

- #### Name: Aditya Thakur

- #### Discord Username(if exists): adityathakur#5048

- #### Additional Context:
 I first hosted Eddie for the closing ceremony of Game of Source (a 10-day long open source event) and have been since following him on LinkedIn and YouTube. I got more involved in the community with MLH Local Hack Build.

  I have recently started with open-source contribution and all throughout this journey all Eddie's videos have been so helpful. I want to be part of the community so I can add value and contribute in any way possible however small.

:nerd_face:

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
