### ISSUE TITLE
Please invite me to the GitHub Community Organisation.

### ISSUE THREAD

**Issue by Melocoder** [EddieJaoudeCommunity/support#719]
Name: Onyeocha Melody

Additional Context:
Where did you meet Eddie?

Found his channel on youtube and i immediately liked his teaching pattern. I'm still very new to open source and i see this as an opportunity to start my journey into open source.

What do you like about this community/ why do you want to join?

I like how contribution from everyone matters and how people get to learn from each other and help each other grows.

I also love how the community has a mix of people from every level of expertise from noob to pro that means i get to learn from different people and their experiences

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
