### ISSUE TITLE
Repo / Website for our community, what we do, why, etc

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/support#72]
Open for discussion. 

I created a repo already https://github.com/EddieJaoudeCommunity/EddieJaoudeCommunity.github.io

**Comment by stemount** [comment]
Looks good to me, this ticket is done, all new discussions over on the issue queue of the above repo.

**Comment by eddiejaoude** [comment]
Thanks @stemount 👍
