### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by rohank2502** [EddieJaoudeCommunity/support#723]
Please invite me to the GitHub Community Organisation. I am exited About contributing in Open-Source.

 Name: Rohan Kulkarni

- #### Discord Username(if exists):  Rohank2502#9618

Where did you meet Eddie?
I came to know about him as a Git-Hub Star from Code for Cause Youtube Channel. 

What do you like about this community/ why do you want to join?
I am a first-year Btech student. I am curious regarding the open-source community. I will like to contribute to open source. As I am learning Cpp and Python and Also Front end development it will be helpful for a beginner like me to get guidance from the experts. And surely my journey will be amazing

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
