### ISSUE TITLE
Invitation to organisation

### ISSUE THREAD

**Issue by ritvij14** [EddieJaoudeCommunity/support#73]
**Description**
Hi, My name is Ritvij, a 2nd-year student pursuing my B.E. I am a passionate developer and would like to join your community to learn more about Open Source, working in teams, collaborating on projects, and lot more fun topics.

**Comment by eddiejaoude** [comment]
Invitation sent @ritvij14 , dont forget to make it public if you want people to see it on your profile - you can do this by finding your name here after accepting the invitation and change it to public https://github.com/orgs/EddieJaoudeCommunity/people
