### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by Vrukshali-26** [EddieJaoudeCommunity/support#730]
Please invite me to the GitHub Community Organisation. 

- #### Name: Vrukshali 

- #### Discord Username(if exists): 

- #### Additional Context: 

 
I have seen lots of YouTube videos of Eddie. He always encourages people to join the open source community. 
I met Eddie at Local Hack Day: Build and I was also a part of eddiehub guild which was really a great fun !!  I like helping nature of the community : )
I am here to learn lots of new stuffs and get connected to lots of new people !!
:nerd_face:

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
