### ISSUE TITLE
Disable Mee6 Automated Welcomes

### ISSUE THREAD

**Issue by nhcarrigan** [EddieJaoudeCommunity/support#743]
**Description**

Our Discord community has grown (and continues to grow) to the point that the Mee6 automated welcome messages are flooding the `introductions` channel, preventing new members from actually introducing themselves. Given that we are active enough now that most (if not all) new members receive a welcome from a live human person, we discussed switching off the automated welcome message in our Discord community.

Ref: [Discord discussion](https://discord.com/channels/699608417039286293/703901317457903687/802576689581654056)

**Comment by nhcarrigan** [comment]
Closing this as @eddiejaoude has resolved it. 🙂

**Comment by eddiejaoude** [comment]
Thanks 👍
