### ISSUE TITLE
Review my Node.js Discord Bot boilerplate

### ISSUE THREAD

**Issue by GarfDev** [EddieJaoudeCommunity/support#761]
Items we can review on a live stream: 

1. Discord Bot Boilerplate (Nodejs, Typescript)
can open repo in here: [Discord Bot Boilerplate](https://github.com/GarfDev/best-discord-bot-typescript-template-ever)

 
- GitHub profile
- Open source project
- Portfolio

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of Eddie Jaoude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
@GarfDev did you mean to close this?
