### ISSUE TITLE
Hey, please add me to the community

### ISSUE THREAD

**Issue by Jaynil1611** [EddieJaoudeCommunity/support#8]
### Hey, I am Jaynil Gaglani. I am currently pursuing B.Tech in I.T .engineering from India.
- I work on full-stack development involving React, Angular, NodeJS, Firebase, Micronaut.
- I am also interested in machine learning and Open Source contribution.
- Check out my GitHub and LinkedIn profiles:
  - [LinkedIn](https://www.linkedin.com/in/jaynilgaglani/)
  - [GitHub](https://github.com/Jaynil1611)

**Comment by eddiejaoude** [comment]
Added 👍 

Don't forget to make it public in the people list if you want it to appear in your profile 🤓

**Comment by Jaynil1611** [comment]
Thanks. I will make it public
