### ISSUE TITLE
Modify README.md to reflect new feature "Discussions"

### ISSUE THREAD

**Issue by Ruth-ikegah** [EddieJaoudeCommunity/support#83]
**Description**
The README.md file in this repository does not reflect the new discussions feature, so people still ask questions with creating an issue.

**Desired Behavior**
Add to the README file saying for a question, check out the discussion area and submit your questions.

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Thanks @Ruth-ikegah 👍 

You are right, we should be more clear, what goes in the Issues and what goes in the Discussion section.

I think something like this:

- Actions go in the Issues
   - bug
   - add me to the org
   - etc
- Everything else in Discussions
   - Questions
   - Ideas (then once discussed an Issue could be created and linked to the Discussion thread)
   - etc

**Comment by Abiola-Farounbi** [comment]
I would like to be assigned to this issue

**Comment by eddiejaoude** [comment]
sure @Abiola-Farounbi 👍 . I have assigned it to you, thank you 🤓 - any questions please let us know

**Comment by Ruth-ikegah** [comment]
> I would like to be assigned to this issue

Nice!

**Comment by eddiejaoude** [comment]
I think that has now been done. I will close this and we can create a new issue when required

<img width="1170" alt="Screenshot 2020-10-24 at 10 14 11" src="https://user-images.githubusercontent.com/624760/97078128-b2694380-15e1-11eb-8295-b3943a912019.png">
