### ISSUE TITLE
NOT A REAL ISSUE: Fork to remind eddie to add me to the group :)

### ISSUE THREAD

**Issue by JNBarr** [EddieJaoudeCommunity/support#84]
**Description**

A brief description of the question or issue:

You can also join the discord community [here](https://discord.com/invite/jZQs6Wu)

Feel free to check out other cool repositories of EddieJoaude Community [here](https://github.com/EddieJaoudeCommunity)

**Comment by eddiejaoude** [comment]
Organisation invitation sent 🎉 

After accepting the invitation. You will need to make it public to appear on your profile. You can do this by finding your name in the `people` list and changing it to `public` - only you can do this for your profile https://github.com/orgs/EddieJaoudeCommunity/people
