### ISSUE TITLE
How to read whole RAM?

### ISSUE THREAD

**Issue by mohit01-beep** [EddieJaoudeCommunity/support#89]
**Description**

I want to read my RAM i mean Whole RAM so that i can see every part of my RAM 
also like when we write programs in any language and declare any variable we usually say that it stored in RAM but how can we prove it

**Comment by eddiejaoude** [comment]
What information / examples have you found already?

**Comment by mohit01-beep** [comment]
I found but I didn't get how to do that there's lot of thing going on in that process

**Comment by mohit01-beep** [comment]
anyone know how to do that?

**Comment by eddiejaoude** [comment]
> I found but I didn't get how to do that there's lot of thing going on in that process

Your question is too generic. What did you find? which part did you not understand or get stuck on? what was the error you got when you tried?

**Comment by stemount** [comment]
@mohit01-beep I think what you are asking for is "Where is the memory address" for my variable.

This is completely different for all languages/compilers/runtimes/JIT/whatever (memory pointers)

I'd look into how languages such as C and Java manages memory/garbage collection/stack to find out about memory pointers/memory addresses etc.

This is a hugely complex thing to answer and requires a lot of time to understand the above. (so it is not really a simple answer IMO)

**Comment by mohit01-beep** [comment]
@stemount thanks for telling that, so is there only 1 way or other ways to find out that answer
