### ISSUE TITLE
Mute command issue

### ISSUE THREAD

**Issue by SalihGhauri** [EddieJaoudeCommunity/support#9]
I have created a mute command for my discord bot and when I mute the user it dm's the user this layout: https://cdn.discordapp.com/attachments/699880048504733747/737701640928362586/unknown.png
But I want it do this layout but for some reason, it is not working https://cdn.discordapp.com/attachments/699880048504733747/737701923263610930/unknown.png
I was wondering if anyone can help me

https://cdn.discordapp.com/attachments/708825001456828427/737707775941017610/unknown.png

**Comment by alrifay** [comment]
Note unrelated to the issue 😄: 
To add an image in markdown, use is syntax:
`![Alt Text](url)`

For example:
`![user message](https://cdn.discordapp.com/attachments/699880048504733747/737701640928362586/unknown.png)`
![user message](https://cdn.discordapp.com/attachments/699880048504733747/737701640928362586/unknown.png)

For more details check out [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
from [Github Guides](https://guides.github.com/)

**Comment by eddiejaoude** [comment]
Great tip @alrifay 👍 , thanks for the question @SalihGhauri 🤓 

The original message will look like this with formatting...

> I have created a mute command for my discord bot and when I mute the user it dm's the user this layout: 
![screenshot](https://cdn.discordapp.com/attachments/699880048504733747/737701640928362586/unknown.png)
But I want it do this layout but for some reason, it is not working 
![screenshot](https://cdn.discordapp.com/attachments/699880048504733747/737701923263610930/unknown.png)
I was wondering if anyone can help me
![screnshot](https://cdn.discordapp.com/attachments/708825001456828427/737707775941017610/unknown.png)

**Comment by eddiejaoude** [comment]
To get the layout, you need to use `embeds` https://discordjs.guide/popular-topics/embeds.html

From their documentation...
```js
// at the top of your file
const Discord = require('discord.js');

// inside a command, event listener, etc.
const exampleEmbed = new Discord.MessageEmbed()
	.setColor('#0099ff')
	.setTitle('Some title')
	.setURL('https://discord.js.org/')
	.setAuthor('Some name', 'https://i.imgur.com/wSTFkRM.png', 'https://discord.js.org')
	.setDescription('Some description here')
	.setThumbnail('https://i.imgur.com/wSTFkRM.png')
	.addFields(
		{ name: 'Regular field title', value: 'Some value here' },
		{ name: '\u200B', value: '\u200B' },
		{ name: 'Inline field title', value: 'Some value here', inline: true },
		{ name: 'Inline field title', value: 'Some value here', inline: true },
	)
	.addField('Inline field title', 'Some value here', true)
	.setImage('https://i.imgur.com/wSTFkRM.png')
	.setTimestamp()
	.setFooter('Some footer text here', 'https://i.imgur.com/wSTFkRM.png');

channel.send(exampleEmbed);
```
