### ISSUE TITLE
'Edit' a form - MySQL database with PHP (CRUD)

### ISSUE THREAD

**Issue by natelloyd1** [EddieJaoudeCommunity/support#93]
**Description**

I'm trying to 'edit' a job name in the MySQL database by clicking 'edit'.  I'd then like for the job name to change back to an input field, like it is when you 'create' a job. 

I have the 'delete' function working and used some code from that, but at the moment the web app is just refreshing. 
I'm not sure how to write the html/php for the front-end.

If I remove 

`mysqli_close($con); 
  header("Location: /www.studioplanner.com");`

then the URL will show that it's targeting a job, for example '../edit.php?id=49' , so that's a start?

Here is the code I've used for the front end - 

                                      `!-- Title -->
	                                <div class="title full-width client-<?php echo $client; ?>">

	                                	<?php echo $type; ?>
	                                    <?php echo $jobtitle; ?>
	                                    
	                                    
	                                    <form action="delete.php?id=<?php echo $row['id']; ?>" method="post" name="planner">
	                                        <input class="button transition-250" id="submit" type="submit" name="vote" value="x">
	                                    </form>

	                                    
	                                    <form action="edit.php?id=<?php echo $row['id']; ?>" method="post" name="planner">
	                                        <input class="button transition-250 edit" id="submit" type="submit" name="vote" 
                                                  value="edit">
	                                    </form>

	                                </div>

                            
                            <form action="create.php?people=<?php echo $people_title; ?>&day=<?php echo $day_title; ?>" 
                              method="post" name="planner">   
                                <input class="transition-250" style="border-color: #d1d1d1; font-size: 14px;" type="text" id="" 
                                   name="job" placeholder="" required>
                                <input class="update-button transition-250" id="submit" type="submit" name="vote" value="ADD" 
                                  style="">
                            </form>  `

**Stack**

PHP, MySQL

**Working Environment**

Mac, VS Code
Chrome

**Screenshots**

![Screenshot 2020-08-24 at 12 21 49](https://user-images.githubusercontent.com/57069051/91039595-bd651f00-e604-11ea-8aae-57f2d7ea04e8.png)

![Screenshot 2020-08-24 at 12 37 11](https://user-images.githubusercontent.com/57069051/91040686-8db71680-e606-11ea-92bc-e0db94e5a9a1.png)

**Comment by eddiejaoude** [comment]
> then the URL will show that it's targeting a job, for example '../edit.php?id=49' , so that's a start?

It is difficult to understand without seeing more of the project. Do you have a GitHub link to the project?

I can take a guess... can you change your `header("location: view.php?id={$id}")` to redirect to the view page

**Comment by natelloyd1** [comment]
@eddiejaoude Thanks Eddie, that's a good idea.  This will take me to a 404 once I click edit, whereas I'm hoping to stay on the page, however I may need to create a replica page to 'edit' each job...
