### ISSUE TITLE
How do I keep my Git fork up to date?

### ISSUE THREAD

**Issue by Shubham714** [EddieJaoudeCommunity/support#94]
since I forked many repositories, I won't be able to keep them all up to date. I used to delete them and fork newer one. Anyone help me to automate this task, so that my fork is always up to date.

**Comment by eddiejaoude** [comment]
I did a video on this recently, to avoid deleting the fork and reforking, any questions let me know https://www.youtube.com/watch?v=vn2SgK4IbiM

**Comment by eddiejaoude** [comment]
@Shubham714 did that help?

**Comment by Shubham714** [comment]
Yes 😊

**Comment by eddiejaoude** [comment]
Ok great, can you close this issue please.

If you have anymore questions, you can create a new Issue or we are moving to Discussions https://github.com/EddieJaoudeCommunity/support/discussions
