### ISSUE TITLE
I'd love to be a part of your community

### ISSUE THREAD

**Issue by BhuvaneshHingal** [EddieJaoudeCommunity/support#96]
***Please guide me that how can I join your organization?***

**Comment by BOLT04** [comment]
Hi @BhuvaneshHingal, @eddiejaoude can invite you to the organization, and then you can choose what repository to contribute too 😃. After you join, you can make your profile public here: https://github.com/orgs/EddieJaoudeCommunity/people.

You can also join our Discord server and chat, the invite link is on the README of this repository.

**Comment by eddiejaoude** [comment]
Invitation sent. Welcome to the community 🎉

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

**Comment by eddiejaoude** [comment]
Thanks @BOLT04 👍
