### ISSUE TITLE
Hi community !

### ISSUE THREAD

**Issue by Shanmuganathan05** [EddieJaoudeCommunity/support#97]
Could you please add me to the community. So that I would learn along and contribute.

**Comment by eddiejaoude** [comment]
Invitation sent. Welcome to the community @Shanmuganathan05 🎉 

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people
