### ISSUE TITLE
I would love to be part of your organisation!

### ISSUE THREAD

**Issue by anubhavbagri** [EddieJaoudeCommunity/support#98]
**Please escort me on how to join your organisation?**

**Comment by eddiejaoude** [comment]
Invitation sent. Welcome to the community 🎉 

Don't forget after accepting to make it public so it appears on your github profile for everyone else to see, you can do this by finding your name in the github organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people
